### ISSUE TITLE
Change README chart colors for us colorbind folk

### ISSUE THREAD

**Issue by jalavosus** [bytedance/sonic#136]
I'll get right to the point: I'm some form of colorbind, as I'm sure plenty of other developers are. While the charts in the README are lovely, it's impossible for me -- and, again, likely many others -- to differentiate between the `stdjson` results and `sonic` results, as they appear to be the same shade of blue, which means that -- at a glance -- it's impossible to actually see what the results are. Using a wider color palette would be incredibly helpful to colorblind developers, and would likely aid non-colorblind developers in quickly parsing the results charts at a quick glance.

Cheers!

**Comment by AsterDY** [comment]
Thanks for the advice. We will try another form of charts that is convenient to read for everyone
