### ISSUE TITLE
Wasm compilation 

### ISSUE THREAD

**Issue by gedw99** [bytedance/sonic#140]
Interesting 

since this uses say to walk the json I assume it’s not using reflection ?

if so then it’s possible this will compile to wasm using tinygo ?

because this uses GOOS / GOARCH specifics it won’t compile to embedded using tinygo though ?

**Comment by chenzhuoyu** [comment]
Not possible under current architecture.

However, we are planning a major refactor in Sonic v2, maybe we will consider this in the architecture design.

Also we must verify that some basic components do work with WASM.
