### ISSUE TITLE
Support for String/number fuzzy conversion

### ISSUE THREAD

**Issue by liugang** [bytedance/sonic#170]
jsoniter support fuzzy decoder feature, it is very useful if we work with php service.

https://jsoniter.com/go-tips.html#stringnumber-fuzzy-conversion

> If you are using jsoniter, enable fuzzy decoders can make life easier working with PHP.

```go
import "github.com/json-iterator/go/extra"

extra.RegisterFuzzyDecoders()
```

Then, no matter the input is string or number, or the output is number or string, jsoniter will convert it for you. For example:

```go
var val string
jsoniter.UnmarshalFromString(`100`, &val)
```
And

```go
var val float32
jsoniter.UnmarshalFromString(`"1.23"`, &val)
```

[] as object

Another heart breaking “feature” of PHP is that, when array is empty, it is encoded as [] instead of {}.

If you are using jsoniter, enable fuzzy decoders will also fix this.
```go
import "github.com/json-iterator/go/extra"

extra.RegisterFuzzyDecoders()
```
Then we can deal with []
```go
var val map[string]interface{}
jsoniter.UnmarshalFromString(`[]`, &val)

```

Without Fuzzy Decoder, the follow code will Unmarshal fail!!!

```go
package main

import (
	"github.com/bytedance/sonic"
	"github.com/bytedance/sonic/decoder"
)

type TestStruct struct {
	Age int `json:"age"`
}

func main() {
	s := "{\"age\": \"10\"}"
	// s := "{\"age\": 10}"
	var data TestStruct
	err := sonic.Unmarshal([]byte(s), &data)
	if err != nil {
		println(err.Error())
		/*pretty print*/
		if e, ok := err.(decoder.SyntaxError); ok {
			print(e.Description())
		}
	}
}
```

```
"Syntax error at index 8: invalid char\n\n\t{\"age\": \"10\"}\n\t........^....\n"
Syntax error at index 8: invalid char

        {"age": "10"}
        ........^....
```

**Comment by AsterDY** [comment]
For str2any or any2str, you can use `string` json tag as encoding/json:
- decoder
```
func TestDecoder_String(t *testing.T) {
    var v struct {
        A int `json:"A,string"`
    }
    _, _ = decode(`{"A":"12345"}`, &v)
    spew.Dump(v) 
/**
(struct { A int "json:\"A,string\"" }) {
 A: (int) 12345
}
**/
}
```
- encoder
```
func TestEncoder_String2(t *testing.T) {
    var v struct {
        A int `json:"A,string"`
    }
    buf, _ := Encode(v, 0)
    println(string(buf))
/**
{"A":"0"}
**/
}
```
As for `[] as object`, I think `json.Unmarshaler` is enough for working around.

**Comment by HaochangZhang** [comment]
PHP传递是弱类型，传递过来的数字有可能是string或者number。json的string tag只能强制使用一种类型
