### ISSUE TITLE
Apple Silicon support 

### ISSUE THREAD

**Issue by Liloupar** [bytedance/sonic#172]
build error on mac m1

**Comment by JOJO0527** [comment]
> build error on mac m1

Me too， at 2020 MacBook Pro， It seems that sonic is only support on amd64platform

**Comment by lima2020-root** [comment]
armv8 platform was not supported.

**Comment by ilovejs** [comment]
plz

**Comment by chenzhuoyu** [comment]
This will be a major design change. It is very hard to support another processor under the current architecture, and may require a complete redesigning. This will be addressed in the next major release, Sonic v2.

**Comment by alphadose** [comment]
Hello, is there currently a tentative date for the release of v2 ?

Secondly, I can help on this issue if you require it, since I have a M1 mac and its alongside my interests.

Thirdly, since generics was released with go stable 1.18 recently, any plans on using them to improve performance even more on v2 ?

**Comment by Larry-Z** [comment]
Could you add a skip mechanism （for AVX or other ASM code）to compile successfully. Because most people edit projects on macbook. After compile success，submit codes to git.  Debug or running on Linux.

**Comment by hwzp99** [comment]
support mac m1

**Comment by dmxbb** [comment]
anxiously waiting for v2.

**Comment by shopee-jin** [comment]
+2000

**Comment by chenzhuoyu** [comment]
We have implemented a compatibility layer (#233) recently.

This is just a thin wrapper around `encoding/json` as a fallback, so don't expect high performance on Apple Silicon chips for now, but it can serve as a workaround to the compilation error and will unblock your development process.

The real native support will be included in the, well, Sonic v2, which we are still actively developing.

For those who want to use Sonic on Apple Silicon Macs, this might be a viable solution for now.

**Comment by shopee-jin** [comment]
export GOARCH=amd64

**Comment by imraan-go** [comment]
What about amazon Graviton processors?

**Comment by AsterDY** [comment]
at present, set GOARCH=amd64 and use Rosatta is enough (https://github.com/bytedance/sonic#compatibility). For better performance and really support `ARM` arch in future, we still have a lot of jobs to do:
1. `asm2asm` tool supports converting ARM assembly into Plan9
2. ARM version of SIMD algorithm for native function `Skip()\Value()\u64toa()`...
3. alternative JIT assembler which supports ARM assembly
All these need much time to develop and test. Maybe in our next major version we can finish it, in the most optimistic case

**Comment by guanzhanyi** [comment]
> at present, set GOARCH=amd64 and use Rosatta is enough (https://github.com/bytedance/sonic#compatibility). For better performance and really support `ARM` arch in future, we still have a lot of jobs to do:
> 
> 1. `asm2asm` tool supports converting ARM assembly into Plan9
> 2. ARM version of SIMD algorithm for native function `Skip()\Value()\u64toa()`...
> 3. alternative JIT assembler which supports ARM assembly
>    All these need much time to develop and test. Maybe in our next major version we can finish it, in the most optimistic case

I already installed Rosatta2 and set GOARCH=amd64. But it still does not work when i build with goland. What should I do?

**Comment by BrianYi** [comment]
> 

but I still cannot debug program, it would not stop at breakpoint.

**Comment by BrianYi** [comment]
> > > at present, set GOARCH=amd64 and use Rosatta is enough (https://github.com/bytedance/sonic#compatibility). For better performance and really support `ARM` arch in future, we still have a lot of jobs to do:
> > > 
> > > 1. `asm2asm` tool supports converting ARM assembly into Plan9
> > > 2. ARM version of SIMD algorithm for native function `Skip()\Value()\u64toa()`...
> > > 3. alternative JIT assembler which supports ARM assembly
> > >    All these need much time to develop and test. Maybe in our next major version we can finish it, in the most optimistic case
> > 
> > 
> > I already installed Rosatta2 and set GOARCH=amd64. But it still does not work when i build with goland. What should I do?
> 
> After i upgrade v1.3 to v.15, it success

but I still cannot debug program, it would not stop at breakpoint.

**Comment by jsrz** [comment]
Is there an ETA on Sonic V2 with native aarch64/Arm64/M1/Graviton/etc. support?

**Comment by odidev** [comment]
Hi @AsterDY and @chenzhuoyu, 

If arm64 support becomes available, it will be really beneficial. If you need any assistance, I am happy to help with testing or any other.

**Comment by AsterDY** [comment]
Build and run is OK. You mean performance?

**Comment by AsterDY** [comment]
> The ARM support is still not available
Build and run is OK. You mean performance?

**Comment by maverick-ai** [comment]
I am trying to run it inside docker with golang:alpine image running it on M1. It does not built

**Comment by AsterDY** [comment]
Not support. Alpine lacks features needed for running sonic. Just use normal linux OS
