### ISSUE TITLE
Question: Exposing internal package as external/separated repository

### ISSUE THREAD

**Issue by ii64** [bytedance/sonic#175]
It seems that the JIT is generic that can be useful outside the sonic itself so that it can be used by others

**Comment by AsterDY** [comment]
> It seems that the JIT is generic that can be useful outside the sonic itself so that it can be used by others

Maybe in our next major version, or another jit-implemented library? @chenzhuoyu

**Comment by chenzhuoyu** [comment]
@ii64 It's quite the opposite. Sonic JIT is not generic at all, it is designed specifically for Sonic, and this is the reason why it's  currently very hard to port to other architectures or ABIs.

In the next major release (e.g. Sonic v2), we are planning for a more generic JIT backend architecture. This new JIT backend will become it's own library, instead being part of Sonic. At that time maybe you can just use the new library.
