### ISSUE TITLE
反序列化结构中的字符串是不安全的

### ISSUE THREAD

**Issue by andot** [bytedance/sonic#191]
```go
import (
	"bytes"
	"encoding/json"
	"testing"

	"github.com/bytedance/sonic"
	jsoniter "github.com/json-iterator/go"
	"github.com/stretchr/testify/require"
)

func TestSonicUnmarshal(t *testing.T) {
	type test struct {
		Str1 string
		Str2 string
	}
	buf := bytes.NewBuffer(make([]byte, 0, 4096))
	data, _ := sonic.Marshal(test{"1234567", "7654321"})
	buf.Write(data)
	var s test
	sonic.Unmarshal(buf.Bytes(), &s)
	require.Equal(t, "1234567", s.Str1)
	require.Equal(t, "7654321", s.Str2)
	buf.Reset()
	data, _ = sonic.Marshal(test{"7654321", "1234567"})
	buf.Write(data)
	require.Equal(t, "1234567", s.Str1)
	require.Equal(t, "7654321", s.Str2)
}

func TestStdJsonUnmarshal(t *testing.T) {
	type test struct {
		Str1 string
		Str2 string
	}
	buf := bytes.NewBuffer(make([]byte, 0, 4096))
	data, _ := json.Marshal(test{"1234567", "7654321"})
	buf.Write(data)
	var s test
	json.Unmarshal(buf.Bytes(), &s)
	require.Equal(t, "1234567", s.Str1)
	require.Equal(t, "7654321", s.Str2)
	buf.Reset()
	data, _ = json.Marshal(test{"7654321", "1234567"})
	buf.Write(data)
	require.Equal(t, "1234567", s.Str1)
	require.Equal(t, "7654321", s.Str2)
}

func TestJsoniterUnmarshal(t *testing.T) {
	type test struct {
		Str1 string
		Str2 string
	}
	json := jsoniter.ConfigFastest
	buf := bytes.NewBuffer(make([]byte, 0, 4096))
	data, _ := json.Marshal(test{"1234567", "7654321"})
	buf.Write(data)
	var s test
	json.Unmarshal(buf.Bytes(), &s)
	require.Equal(t, "1234567", s.Str1)
	require.Equal(t, "7654321", s.Str2)
	buf.Reset()
	data, _ = json.Marshal(test{"7654321", "1234567"})
	buf.Write(data)
	require.Equal(t, "1234567", s.Str1)
	require.Equal(t, "7654321", s.Str2)
}
```
如果把 sonic 换成 json 或者 jsoniter，都能测试通过，而 sonic 则会报错，因为它反序列化结果中的 string 字段会直接引用输入参数中的值，如果在反序列化之后，输入参数被修改，则会导致反序列化结果错乱。

**Comment by AsterDY** [comment]
是的。由于decoder底层存储的是string，出于性能考虑做了unsafe转换。你可以在传入Unmarshal之前先做一次[]byte拷贝

**Comment by andot** [comment]
现在为了避开这个 bug，我们是做了一次 []byte 拷贝，但是这仍然避免不了大块的内存因为被结构体中的字符串字段引用，而导致整个大块的内存无法释放的问题。总之，这个地方不应该直接对输入的数据做 unsafe 转换，而且如果只有对输入参数做一次拷贝才能让反序列化的结果正常读取的话，那还会导致我们本来的内存池就等于形同虚设了。我们本来用内存池，就是为了避免重复申请大块内存。

**Comment by AsterDY** [comment]
问题不是“直接对输入的数据做 unsafe 转换”，而是“大块的内存被结构体中的字符串字段引用”。所以应该只拷贝你的json。之前是sonic帮你拷贝一次，v1.0.2之后需要自己拷贝

**Comment by andot** [comment]
举个例子，比如输入的数据是 ```[]byte(`{"str1":"1234567","str2":"7654321"}`)```，反序列化的结构体中，现在 `str1` 和 `str2` 这两个字段值会直接引用输入数据中的 `"1234567"`, `"7654321"` 这两个判断，而不是把这两个值单独复制一份出来。这样会有两个副作用，第一个副作用是如果输入的这个 `[]byte` 源中的值被修改，则反序列化结构体中的字符串字段也会一同被修改。第二个副作用是，如果反序列化的结构体会被长期使用（比如反序列化的结构体被缓存），则输入的 `[]byte` 源这一大块 json 内存都不会被释放。正常情况下，如果存在这两个副作用，都不应该使用 unsafe 转换。unsafe 转换只应该用在不会发生这两种副作用的局部代码中。所以，这个实现是对 unsafe 转换的错误用法，虽然能提高跑分效果，但是也仅仅只能让跑分数字好看，实际使用会带来的问题都是不可预测的。正确的做法是，在处理数字、bool等字段时，可以引用输入数据中的原始数据然后做转换，而不必先复制一个字符串再用复制出来的字符串做转换，但是对于[]byte、string这种字段，一定要对这个字段值复制一个副本出来赋值给这些字段，而不应该用 unsafe 方式直接引用输入数据中的片段作为字段值。

**Comment by andot** [comment]
你说之前是 sonic 做了整体拷贝，v1.0.2 之后需要自己拷贝。这两种做法其实都是错误的。正确的做法是，不管是 sonic 还是用户都不做整体拷贝，只对反序列化字段中的 []byte 和 string 字段部分做拷贝操作，其它字段都不需要做拷贝操作。这样既能保证高效，也不会导致输入数据修改会影响反序列化结果，还不会导致大块的输入 json 无法被释放。

**Comment by AsterDY** [comment]
“只对反序列化字段中的 []byte 和 string 字段部分做拷贝操作”这个之前测试过了，对性能的影响大概在10%～20%

**Comment by andot** [comment]
性能要在保证正确性的情况下才有效，如果不能保证正确性，再快也是没用的。

**Comment by AsterDY** [comment]
安全性问题可以通过用法约束来避免。主要是冗余的json内存引用可能会对cache型服务产生较大影响。我们后面加个选项吧。

**Comment by andot** [comment]
我想大部分用户第一次使用时在掉到坑里之前应该不会想到这个安全性问题的，毕竟 README 里面也没写，昨天因为这个问题，导致系统出错了一个小时。领导一开始看这个库跑分不错就像拿来试试，踩到坑之后，领导再也不敢用了![9DBB76BE0A98F5E2922EE3C04EC64156](https://user-images.githubusercontent.com/232161/155359784-c4f678d7-084e-4dab-824d-5d2ccb766020.png)
