### ISSUE TITLE
decodeTypedPointer panic 

### ISSUE THREAD

**Issue by jank1369** [bytedance/sonic#199]
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f07d800953c]

goroutine 1 [running]:
runtime.throw({0x1414f52, 0xcfabd3})
	runtime/panic.go:1198 +0x71 fp=0xc0004fd8d8 sp=0xc0004fd8a8 pc=0x829371
runtime.sigpanic()
	runtime/signal_unix.go:742 +0x2f6 fp=0xc0004fd928 sp=0xc0004fd8d8 pc=0x83fa16
runtime.__json_decoder_7f07d8006000()
	?:0 +0x353c fp=0xc0004fda28 sp=0xc0004fd928 pc=0x7f07d800953c
github.com/bytedance/sonic/decoder.decodeTypedPointer({0xc007a98000, 0x8810}, 0x8, 0xa000, 0x0, 0x7f07d81e4100, 0x2)
	github.com/bytedance/sonic@v1.1.1/decoder/primitives.go:33 +0xb0 fp=0xc0004fdaa8 sp=0xc0004fda28 pc=0xd6e250
github.com/bytedance/sonic/decoder.(*Decoder).Decode(0xc0004fdb68, {0x1279e60, 0xc0008b3580})
	github.com/bytedance/sonic@v1.1.1/decoder/decoder.go:73 +0xec fp=0xc0004fdb48 sp=0xc0004fdaa8 pc=0xd59e0c
github.com/bytedance/sonic.UnmarshalString({0xc007a98000, 0x0}, {0x1279e60, 0xc0008b3580})
	github.com/bytedance/sonic@v1.1.1/sonic.go:46 +0x67 fp=0xc0004fdbb8 sp=0xc0004fdb48 pc=0xd815c7

**Comment by chenzhuoyu** [comment]
@AsterDY

**Comment by AsterDY** [comment]
Seems like a GC problem...If you can provide reproducible codes, it will help a lot
