### ISSUE TITLE
Go 1.18 support

### ISSUE THREAD

**Issue by mosajjal** [bytedance/sonic#201]
Getting the following error after update to 1.18:

```
("Unsupported Go version. Supported versions are: 1.15, 1.16, 1.17") (no value) used as value...
```

Don't think 1.18 is fundamentally different than 1.17 so we can just add the version in? Although that "no value" doesn't look good

**Comment by ii64** [comment]
Go 1.18 has difference on module function registration which sonic use to register JIT func address to be identified by Golang runtime.

**Comment by mosajjal** [comment]
ah I see. is this development currently underway? I can go take a look but looks to be out of my league :P I just use it in my own project and I'm keen to pivot to `generics` hence asking for 1.18

**Comment by ii64** [comment]
Here https://github.com/bytedance/sonic/tree/feat/go118
