### ISSUE TITLE
high ram cached+buffer after upgrade sonic

### ISSUE THREAD

**Issue by zdyj3170101136** [bytedance/sonic#204]
after use sonic to replace gogo/jsonpb to marshal protobuf to json.
my ram cached+buffer upgrade from 9gb to 16 gb.

**Comment by ii64** [comment]
Please provide more detail like which sonic version, or memory profile result. Is the struct big, or having complex data structure?

**Comment by AsterDY** [comment]
your application is a caching service? https://github.com/bytedance/sonic#copy-string may help
