### ISSUE TITLE
Marshal: precision diff with stdjson on float32

### ISSUE THREAD

**Issue by littleRa1n** [bytedance/sonic#21]
example code:
f := map[string]float32{
"value": 0.006072998046875,
}

b1, _ := json.Marshal(f)
b2, _ := sonic.Marshal(f)

fmt.Println(string(b1))
fmt.Println(string(b2))

**Comment by AsterDY** [comment]
Since it's not a precision loss and json RFC suggests to use float64, we think it is unnecessary to handle this at present
