### ISSUE TITLE
sonic.Unmarshal decode json string failed when field's type is "stringint" 

### ISSUE THREAD

**Issue by gy0624ww** [bytedance/sonic#211]
test code below:
```
type P struct {
	Cip        string      `json:"cip"`
	Oip        string      `json:"oip"`
	Oid        string      `json:"oid"`
	Aid        json.Number `json:"aid"`
	Pcid       string      `json:"pcid"`
        Num        int `json:"num"`
}

func main() {
	var pstruct P
	jsonStr := `{"num":123, "cip":"127.0.0.1","oip":"10.206.85.204",oid":"52852","aid":"6079759","pcid":"75","cid":"76"}`
	//json.Unmarshal([]byte(jsonStr), &pstruct)
	sonic.Unmarshal([]byte(jsonStr), &pstruct)
	fmt.Println(pstruct.Cip) // output: "127.0.0.1"
      fmt.Println(pstruct.Num) // output:123
      fmt.Println(pstruct.Aid) // output: ""
      fmt.Println(pstruct.Oid) // output: ""
}
```

if this is normal, how make this print correctly?
PS:
sonic v1.1.1
------------------------------
i found out the problem rule: when the type of struct defined is not match with the json, the field and the fields behind it all empty.
eg :
```
type Test struct {
     Num1 string `json:"num1"`
     Num2 string `json:"num2"`
     Num3 string `json:"num3"`
     Num4 string `json:"num4"`
     Num5 string `json:"num5"`
 }
testStr := `{"num1":"123","num2":"this is string2", "num3":456, "num4":789, "num5":"this is string"}`
var t Test
sonic.Unmarshal([]byte(testStr), &t)
fmt.Printf("%#v", t)
//output:  {Num1:"123", Num2:"this is string2", Num3:"", Num4:"", Num5:""}
```

**Comment by chenzhuoyu** [comment]
It seems that you have ignored the returned error. Please ensure `sonic.Unmarshal` returns `nil` before using the unmarshaled value, otherwise it's undefined behavior.

**Comment by gy0624ww** [comment]
您发送给我的邮件 我已经收到了
所以，请您放心吧

**Comment by chenzhuoyu** [comment]
> ```
> jsonStr := `{"num":123, "cip":"127.0.0.1","oip":"10.206.85.204",oid":"52852","aid":"6079759","pcid":"75","cid":"76"}`
> ```

If you print out the error description, you will find that this JSON string is invalid:

```
Syntax error at index 52: invalid char

	"10.206.85.204",oid":"52852","ai
	................^...............
```

**Comment by gy0624ww** [comment]
> It seems that you have ignored the returned error. Please ensure `sonic.Unmarshal` returns `nil` before using the unmarshaled value, otherwise it's undefined behavior.

but, even if I catch the error, what could I do next, should not terminate the program. Native json behavior is just prase the wrong type filed empty, no effect the others.

**Comment by gy0624ww** [comment]
@chenzhuoyu 我觉得这种行为是极其不友好的，而且报错的信息也非结构化信息，而且这类型错误直接影响后面的字段的输出，也逻辑也不对吧。这块能否改善下。
错误结构化输出
错误只标识类型错误字段，不影响其他字段的输出。这样是以warning级别记录，对程序兼容性好一些。

而且我提的问题也不是json语法的问题，那个是笔误 少些个双引号。我提的问题是类型不一致的问题。
用下面的就能复现。
```
type Test struct {
     Num1 string `json:"num1"`
     Num2 string `json:"num2"`
     Num3 string `json:"num3"`
     Num4 string `json:"num4"`
     Num5 string `json:"num5"`
 }
testStr := `{"num1":"123","num2":"this is string2", "num3":456, "num4":789, "num5":"this is string"}`
var t Test
sonic.Unmarshal([]byte(testStr), &t)
fmt.Printf("%#v", t)
//output:  {Num1:"123", Num2:"this is string2", Num3:"", Num4:"", Num5:""}

**Comment by gy0624ww** [comment]
这问题关了，要不我重新开一个？
