### ISSUE TITLE
sonic.Unmarshal decode json string failed when field's type is "stringint"

### ISSUE THREAD

**Issue by gy0624ww** [bytedance/sonic#212]
i found out the problem rule: when the type of struct defined is not match with the json, the field and the fields behind it all empty.

```
type Test struct {
     Num1 string `json:"num1"`
     Num2 string `json:"num2"`
     Num3 string `json:"num3"`
     Num4 string `json:"num4"`
     Num5 string `json:"num5"`
 }
testStr := `{"num1":"123","num2":"this is string2", "num3":456, "num4":789, "num5":"this is string"}`
var t Test
sonic.Unmarshal([]byte(testStr), &t)
fmt.Printf("%#v", t)
//output:  {Num1:"123", Num2:"this is string2", Num3:"", Num4:"", Num5:""}
```
如果有一个字段类型不匹配的话，那么他后面的字段都会变成空值。我觉得这个处理很不友好吧。直接影响了其他字段的值。
而且err可以捕获，但是错误非结构化信息，无法针对化处理，原生json处理并不会影响后续字段解析。

之前的问题还没讨论结果就关闭了，最好问题明确之后再关闭，谢谢
@chenzhuoyu @AsterDY

**Comment by liuq19** [comment]
Not check errors in both unmarshaling. 
If there are any errors in Unmarshal API, the result may be undefined. So, the result may be different from `encoding/json`.

**Comment by gy0624ww** [comment]
> Not check errors in both unmarshaling. If there are any errors in Unmarshal API, the result may be undefined. So, the result may be different from `encoding/json`.

不会undefined,结果会一样输出，看第几个字段类型不对，比如从第三个字段类型不对，那么前两个字段是有值的，从第三个之后是为空。
而且unmarsha 错误检查，你的意思是上面的例子只要有一个上游传的类型不对就应该终止程序吗？
还有重点是会影响其他字段的值这块，第三个字段类型不对，为什么会影响后面的值。

**Comment by AsterDY** [comment]
No plans for that. Why does your application rely on an **undocumented behavior**? It's dangerous and non-standard.

**Comment by PureWhiteWu** [comment]
在 Go 中，如果有 error，那么默认返回的值是无效值，需要直接丢弃而不能使用。
这个感觉不是问题？
