### ISSUE TITLE
Support for Go 1.18

### ISSUE THREAD

**Issue by bigfoot31** [bytedance/sonic#214]
Can't install for go 1.18. It should be compatible?

![image](https://user-images.githubusercontent.com/14835245/161002221-cbb7ca8f-2c93-4180-888e-ed86b7df77b0.png)

**Comment by ii64** [comment]
Go 1.18 support at https://github.com/bytedance/sonic/commit/cb1702dc8c92727ff90434c27b81fb6dc072304b but no semver tag for it.
