### ISSUE TITLE
checkptr: pointer arithmetic result points to invalid allocation

### ISSUE THREAD

**Issue by jixiuf** [bytedance/sonic#226]
fatal error: checkptr: pointer arithmetic result points to invalid allocation
runtime.throw(0x20e8650, 0x40)
/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc007a09a88 sp=0xc007a09a58 pc=0x439ad2
runtime.checkptrArithmetic(0xc005f17000, 0xc007a09b18, 0x1, 0x1)
/usr/local/go/src/runtime/checkptr.go:43 +0xbe fp=0xc007a09ab8 sp=0xc007a09a88 pc=0x408ebe
github.com/bytedance/sonic/ast.quote(0xc008917d20, 0x1cce4d1, 0x16)
/go/pkg/mod/github.com/bytedance/sonic@v1.1.2-0.20220328124343-cb1702dc8c92/ast/encode.go:127 +0x105 fp=0xc007a09b30 sp=0xc007a09ab8 pc=0x142e9c5
github.com/bytedance/sonic/ast.(*Pair).encode(0xc0061fcb90, 0xc008917d20, 0x1, 0x1)
/go/pkg/mod/github.com/bytedance/sonic@v1.1.2-0.20220328124343-cb1702dc8c92/ast/encode.go:204 +0x167 fp=0xc007a09b80 sp=0xc007a09b30 pc=0x142f2a7
github.com/bytedance/sonic/ast.(*Node).encodeObject(0xc0032b4280, 0xc008917d20, 0x1, 0xa)
/go/pkg/mod/github.com/bytedance/sonic@v1.1.2-0.20220328124343-cb1702dc8c92/ast/encode.go:233 +0x255 fp=0xc007a09c08 sp=0xc007a09b80 pc=0x142f635
github.com/bytedance/sonic/ast.(*Node).encode(0xc0032b4280, 0xc008917d20, 0x16, 0x0)
/go/pkg/mod/github.com/bytedance/sonic@v1.1.2-0.20220328124343-cb1702dc8c92/ast/encode.go:82 +0x31f fp=0xc007a09c88 sp=0xc007a09c08 pc=0x142e4df
github.com/bytedance/sonic/ast.(*Node).MarshalJSON(0xc0032b4280, 0x1cce4d1, 0x16, 0x1dbb760, 0xc005a9e480, 0xc005a9e400)
/go/pkg/mod/github.com/bytedance/sonic@v1.1.2-0.20220328124343-cb1702dc8c92/ast/encode.go:45 +0x45 fp=0xc007a09ce0 sp=0xc007a09c88 pc=0x142df25
gitlab.luojilab.com/oms/optimus/models.ItemBiz.MarshalJSON(0x189ee66d81052569, 0x8a, 0xc0067e1200, 0x5, 0x8, 0x0, 0x0, 0x7d, 0xc0062fa700, 0x1e, ...)
/data/src/models/model_item_biz.go:82 +0x41a fp=0xc007a0af18 sp=0xc007a09ce0 pc=0x1840ffa

```

	root, err := sonic.Get(l.Ext)// l.Ext is json.RawMessage 
	if err != nil {
		return nil, err
	}
	for k, v := range commonFields { // a map 
		node := root.Get()k
		if !node.Exists() {		
			root.SetAny(k ,v)
		}
	}

	return root.MarshalJSON()
```

Go version : `1.15.15`

**Comment by chenzhuoyu** [comment]
@AsterDY

**Comment by AsterDY** [comment]
Don't use go build flag `checkptr`, it can't work for sonic

**Comment by jixiuf** [comment]
> Don't use go build flag `checkptr`, it can't work for sonic


thanks .
after update to `v1.2.1`,  it doesn't panic any more .
