### ISSUE TITLE
[GLCC 赛题] 开发arm64汇编到go plan9汇编转换工具

### ISSUE THREAD

**Issue by cloudwegoIce** [bytedance/sonic#231]
**🚩GLCC 高校编程夏令营赛题**
👏欢迎大家参与～
> GLCC 是由中国计算机学会举办的高校开源编程夏令营活动，活动为项目准备了开源奖学金。请在以下链接中报名参与⬇️
>报名链接： [https://www.gitlink.org.cn/glcc/subjects/detail/224](https://www.gitlink.org.cn/glcc/subjects/detail/224)
>关于issue相关问题、解题思路的答疑将在群内进行
<img width="197" alt="image" src="https://user-images.githubusercontent.com/104130938/170914107-081c4538-6e89-4f04-9720-bf5ba9e473be.png">

1、题目描述
sonic是字节自研的一款高性能JSON库，其底层文本处理算子采用C语言开发，并基于go-assembly机制结合汇编转换工具（asm2asm）嵌入到go语言接口中。但是当前的asm2asm工具仅支持x86-64到plan9的转换，限制了sonic在arm架构环境下的使用。随着arm架构芯片的流行，sonic计划支持arm架构，asm2asm工具支持arm64到plan9的转换也在规划之中。

2、编码任务
- 实现一个ARMv8-A汇编到go plan9汇编的转换工具
- 支持命令行交互（linux or macOSX），最好可以直接对原始C文件调用clang（或gcc）生成汇编 (参考https://github.com/bytedance/sonic/blob/main/Makefile)
- 自动生成对应的go函数接口及其单测（可选）

3、技能要求和编程语言
- ARMv8-A 汇编
- Go plan9 汇编 (https://go.dev/doc/asm)
- 编译原理，可以借助第三方lib做前端解析处理
- 实现语言不限

4、预期完成结果
- 将纯c实现的文件（sonic/native/xx.c) 转换为go arm64汇编文件（sonic/internal/native/xx_arm64.s），并且在arm64环境下可跑通go代码单测（sonic/internal/native/native_amd64_test.go)

GitHub 链接：
- sonic - https://github.com/bytedance/sonic
- asm2asm - https://github.com/chenzhuoyu/asm2asm

**Comment by AsterDY** [comment]
由于`native/native.c`里面有大量C代码是依赖intel x86指令集（主要是SIMD）无法在arm环境下编译，想参与的同学可以自己写一些架构无关的代码进行测试，可以参考我搞的示例https://github.com/AsterDY/asmtest

**Comment by kkHAIKE** [comment]
群满员了 想加入

**Comment by AsterDY** [comment]
> 群满员了 想加入 最近正好在做 sonic arm64

可以作为个人兴趣支持吗？我们也是非常欢迎的

**Comment by lxj15398019970** [comment]
请问现在有版本可以支持linux arm64吗？急啊，最近像上arm机器啊
