### ISSUE TITLE
Behaves differently from stdlib in map encoding

### ISSUE THREAD

**Issue by goccy** [bytedance/sonic#24]
The default behavior of `encoding/json` is to sort the map before encoding. This behavior has a significant performance impact and you should implement this feature before comparing it to other libraries. Otherwise, the result will be unfair.

### Reproducible code

```
package main

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/bytedance/sonic"
)

func main() {
	v := map[string]int{
		"a": 1,
		"b": 2,
		"c": 3,
		"d": 4,
	}
	for i := 0; i < 100; i++ {
		expected, err := json.Marshal(v)
		if err != nil {
			panic(err)
		}
		actual, err := sonic.Marshal(v)
		if err != nil {
			panic(err)
		}
		if !bytes.Equal(expected, actual) {
			fmt.Println("failed to encode map")
			fmt.Println("expected:", string(expected))
			fmt.Println("got     :", string(actual))
			break
		}
	}
}
```

**Comment by PureWhiteWu** [comment]
Is this a documented behaviour of the standard library?

**Comment by goccy** [comment]
See https://golang.org/pkg/encoding/json/#Marshal

> The map keys are sorted and used as JSON object keys by applying the following rules, subject to the UTF-8 coercion described for string values above:

**Comment by chenzhuoyu** [comment]
As you know, this behavior hurts performance A LOT, and it's specific to the Go StdLib, [RFC8259](https://datatracker.ietf.org/doc/html/rfc8259) does NOT require sorting the keys.

This library is designed for performance, not a drop-in replacement of the StdLib, so we must drop some performance-killing "features", as long as it still meets the requirements of the RFC, it's a working implementation. It is OK to behave slightly different with the StdLib.

For reproducible tests, we might consider making it optional. You can then manually switch it on at the cost of some performance.

BTW, if you think the benchmark result is unfair, you can always disable key sorting in your library, and benchmark again.

Marked `low-priority` now.

**Comment by goccy** [comment]
Unless you mention that your library is compatible with `encoding/json`, I think it's good to sacrifice functionality for performance 😄 

However, if you want to compare performance with other libraries, you should, to be fair, see if the library you're comparing has an option that doesn't sort the map, and use that if any.
For example, json-iterator/go supported by `SortMapKeys: false` at config . ( Also, my library support too by `json.UnorderedMap()` option )
