### ISSUE TITLE
Is there any way I use the var as an ast.Node?

### ISSUE THREAD

**Issue by ouliuquan** [bytedance/sonic#245]
I don't want a []byte as a sonic.Get([]byte), this will be do a repeat job. I have done this Unmarshal action before.
code:
package main

import (
	"fmt"
	"github.com/bytedance/sonic"
)

type Message struct {
	Timestamp int64  `json:"timestamp"`
	Message   string `json:"message"`
}

func main() {
	const a3 = `{
            "timestamp":1654760858618823,
            "message":"Hi"
        }`
	var d3 Message
	err := sonic.Unmarshal([]byte(a3), &d3)
	if err != nil {

	}
	s1, _ := sonic.Get([]byte(a3))
	s2, _ := sonic.Get(d3)
	messageStr, _ := s1.Get("message").Raw()
	fmt.Printf("messageStr:%v\n", messageStr)
	fmt.Printf("messageStr s2:%v\n", s2)
}

**Comment by AsterDY** [comment]
As desired, you can use ast.NewAny() to contain your struct:
```
s2 := ast.NewAny(d3)
out, err := s2.MarshalJSON()
println(string(out)) \\ "{"timestamp":1654760858618823,"message":"Hi"}"
```
But I don't understand why you want to do this. If your goal is to pass the entire JSON, I recommend you to use ast.NewRaw():
```
s2 := NewRaw(a3)
out, err := s2.MarshalJSON()
println(string(out)) \\ "{ "timestamp":1654760858618823, "message":"Hi" }"
```
This is more effecient.

**Comment by ouliuquan** [comment]
@AsterDY [AsterDY](https://github.com/AsterDY), thank you very much for your answer, I am new and I don't know there are two ways to use, that seems nice for me.
