### ISSUE TITLE
ast.Node Get a key that doesn't exist

### ISSUE THREAD

**Issue by meng-y** [bytedance/sonic#248]
http: panic serving 127.0.0.1:44846: runtime error: invalid memory address or nil pointer dereference
goroutine 2315 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0xd8a3c0, 0x171dd60})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/bytedance/sonic/ast.(*Node).checkRaw(0xc02713a1b0)
        /home/zhounan1/gopath/src/github.com/bytedance/sonic/ast/node.go:159 +0x14
github.com/bytedance/sonic/ast.(*Node).String(0x0)
        /home/zhounan1/gopath/src/github.com/bytedance/sonic/ast/node.go:245 +0x25

my program just like this:

list.Get("res").Index(key).Get("item").Get("json_data").Index(cardKey).String()

When using ast.Node to get a non-existing key, the program will panic. Is there a way to get the null value of the specified type like the get method of simplejson?

**Comment by AsterDY** [comment]
#250

**Comment by meng-y** [comment]
I have seen this solution, If there is a structure with more than three layers, I mean is there a similar method like simple-json to directly use json.Get("a").Get("b").Get("c").MustString(), Instead of checking Ray layer by layer.
Because I only care about the key I want to take, or return a null value of the corresponding type. Now we must first use checkRaw() to judge that it is a very unfriendly operation

**Comment by AsterDY** [comment]
See demo https://github.com/bytedance/sonic/blob/main/issue_test/issue248_test.go

**Comment by meng-y** [comment]
Thank you for the answer, I want to experience sonic, but my business is more complex, and I will have the opportunity to use it in the future
