### ISSUE TITLE
sonic在不支持AVX的amd64服务器上初始化失败，如何避免？

### ISSUE THREAD

**Issue by yc-go** [bytedance/sonic#255]
在不支持AVX的amd64服务器上，应用启动时会报以下错误：

panic: Unsupported CPU, maybe it's too old to run Sonic.

goroutine 1 [running]:
github.com/bytedance/sonic/internal/native.init.0()
        /go/pkg/mod/github.com/bytedance/sonic@v1.3.1/internal/native/dispatch_amd64.go:144 +0x1fb

请问是否可以通过某项设置，来阻止sonic报错，或者降级到标准库也行。

**Comment by chenzhuoyu** [comment]
Sonic 要求至少支持 AVX 指令集。AVX 是 Sandy Bridge 架构开始支持的，这已经是 2011 年的处理器了，支持更古老的架构意义不大。

BTW：目前已知在 M1 芯片上使用 Rosetta 2 运行 x86_64 版本的 Sonic 会报这个错误，因此不通过 Rosetta 2 转译 Sonic
