### ISSUE TITLE
sonic.Get doesn't support `ARM` arch

### ISSUE THREAD

**Issue by mm2175** [bytedance/sonic#257]
![image](https://user-images.githubusercontent.com/30251661/177251904-41c5d936-9ae9-4ba7-890a-d6d40401af3c.png)

There is no sonic.Get() method.

**Comment by chenzhuoyu** [comment]
@AsterDY

**Comment by AsterDY** [comment]
At present, you can only use this API on `amd64` arch

**Comment by OldPilot** [comment]
@AsterDY When will Sonic support ARM arch?

**Comment by AsterDY** [comment]
resolved by #280 , just set `GOARCH=amd64`, then run on Mac M1 or Linux QEMU is ok

**Comment by mm2175** [comment]
Using `GOARCH=amd64` seems break debuging with Goland.
