### ISSUE TITLE
请问v2什么时间发布？

### ISSUE THREAD

**Issue by snowinszu** [bytedance/sonic#260]
有一个排期么？谢谢

**Comment by AsterDY** [comment]
没有确定的时间线，看其他工作安排。最快年底

**Comment by TonyPythoneer** [comment]
請問 v2 有 blueprint 可以參考嘛？

**Comment by tzq0301** [comment]
> 没有确定的时间线，看其他工作安排。最快年底

请问现在是还没有 v2 的排期吗

**Comment by AsterDY** [comment]
WIP. Alpha version may publish in the middle of 2023

**Comment by AsterDY** [comment]
We promise no breaking-change as much as possible. Thus we will release V2 but will still support ARM64
