### ISSUE TITLE
Fails with infinite float type

### ISSUE THREAD

**Issue by zhixinwen** [bytedance/sonic#264]
Example:
```
func TestMarshal(t *testing.T) {
	s := &T{A: math.Inf(1)}
	bytes, err := sonic.Marshal(s)
	assert.NoError(t, err) // fails here
	r := &T{}
	err = sonic.Unmarshal(bytes, r) // fails if the output is from another json lib
	assert.NoError(t, err)
}
```

**Comment by miluchen** [comment]
Based on RFC draft (https://datatracker.ietf.org/doc/html/rfc4627), `Numeric values that cannot be represented as sequences of digits
   (such as Infinity and NaN) are not permitted.` This should not supported IMHO (it's not supported in standard lib encoding/json).
