### ISSUE TITLE
How to interpret single JSON object as an array with one element?

### ISSUE THREAD

**Issue by cxjava** [bytedance/sonic#270]
In Sonic how to handle the json format like below with one struct?

Format A (JSON array with two element):
```
{"name":"xiao","address":["road1","road2"]}
```
Format B (JSON object, yes I know it looks "wrong" but it's what I'm given):
```
{"name":"xiao","address":"road1"}
```

Example code: 

```
package main

import (
	"fmt"
	"strings"

	"github.com/bytedance/sonic/decoder"
)

type Person struct {
	Name    string
	Address []string
}

func testDecode1() {
	var o Person
	var r = strings.NewReader(`{"name":"xiao","address":["road1","road2"]}`)
	var dec = decoder.NewStreamDecoder(r)
	dec.Decode(&o)
	fmt.Printf("%+v\n", o) // {Name:xiao Address:[road1 road2]}
}

func testDecode2() {
	var o Person
	var r = strings.NewReader(`{"name":"xiao","address":"road1"}`)
	var dec = decoder.NewStreamDecoder(r)
	dec.Decode(&o)
	// expected resoult: {Name:xiao Address:[road1]}
	// actual resoult: {Name:xiao Address:[]}
	fmt.Printf("%+v\n", o)
}

func main() {
	testDecode1()
	testDecode2()
}
```

similar like : https://stackoverflow.com/questions/17003823/make-jackson-interpret-single-json-object-as-array-with-one-element

**Comment by AsterDY** [comment]
not supported by std. But u can implement a work-around logic through `json.Unmarshaler`:
- Define a type `ObjectOrSlice`
- Implement `ObjectOrSlice.UnmarshalJSON()` like this: when the first received byte is `[`, calling `Unmarshal(input, &ObjectOrSlice)`; when is not `[`, calling `unmarshal(input, &Object[0])`
