### ISSUE TITLE
mac m1 无法编译

### ISSUE THREAD

**Issue by lee501** [bytedance/sonic#271]
package tequila
	imports tequila/input
	imports tequila/etl
	imports github.com/bytedance/sonic/decoder
	imports github.com/bytedance/sonic/internal/native: build constraints exclude all Go files in go/pkg/mod/github.com/bytedance/sonic@v1.3.4/internal/native

**Comment by JiahaoWei-RH** [comment]
我也遇到了这个问题，请问你是怎么解决的
