### ISSUE TITLE
Go 1.19

### ISSUE THREAD

**Issue by zzdboy** [bytedance/sonic#272]
Go Compilation Error (in ../../pkg/mod/github.com/bytedance/sonic@v1.3.4/internal/loader/funcdata.go:27): undefined: _ModuleData

**Comment by AsterDY** [comment]
Need some time to match...

**Comment by datafeng** [comment]
对语言新版本支持快些就好了。。

**Comment by PureWhiteWu** [comment]
> 对语言新版本支持快些就好了。。

欢迎提交 PR 一起参与贡献。
