### ISSUE TITLE
float32 convert to float64 may lose precision

### ISSUE THREAD

**Issue by AsterDY** [bytedance/sonic#273]
since sonic use 64-digit precision by default, if u marshal a float32 number like 0.1, it will be json '0.10000000149011612' —— this is ok for decoded into another float32 object (still 0.1). However, if it is decoded into a float64 object, the value is 0.10000000149011612 —— instead of expected float64(0.1)
```
func TestMarshalFloat32264(t *testing.T) {
	var f float32 = 0.1
	oe,ee := json.Marshal(f)
	os,es := sonic.Marshal(f)
	require.Equal(t, ee == nil, es == nil)
	// require.Equal(t, string(oe), string(os))

	var f2,f3 float64
	require.Nil(t, json.Unmarshal(oe, &f2))
	require.Nil(t, sonic.Unmarshal(os, &f3))
	require.Equal(t, f2, f3)
}
```
output:
```
--- FAIL: TestMarshalFloat32264 (0.00s)
    /Users/admin/Desktop/kitex/sonic3/issue_test/issue112_test.go:50: 
        	Error Trace:	issue112_test.go:50
        	Error:      	Not equal: 
        	            	expected: 0.1
        	            	actual  : 0.10000000149011612
        	Test:       	TestMarshalFloat32264
```

**Comment by shopee-jin** [comment]
could this be intended behavior? 

because in computer science, you can ONLY compare floats using  
`Math.Abs(a-b)<1e-8` instead of `a==b`

**Comment by shopee-jin** [comment]
moreover, python has no float32 but float64, and JSON could be consumed by a python program

**Comment by AsterDY** [comment]
fixde by #291
