### ISSUE TITLE
cannot compile on M1 mac

### ISSUE THREAD

**Issue by ly3too** [bytedance/sonic#283]
imports github.com/bytedance/sonic/internal/native: build constraints exclude all Go files in /Users/bytedance/go/pkg/mod/github.com/bytedance/sonic@v1.2.0/internal/native

**Comment by yicixin** [comment]
arm is not supported now.
if you want to remove this error，you can set your go enviroment `GOARCH` to `amd64`.

**Comment by yicixin** [comment]
> imports github.com/bytedance/sonic/internal/native: build constraints exclude all Go files in /Users/bytedance/go/pkg/mod/github.com/bytedance/sonic@v1.2.0/internal/native

arm is not supported now.
if you want to remove this error，you can set your go enviroment GOARCH to amd64.

**Comment by AsterDY** [comment]
update to latest version. All M1 machines are supposed to be supported

**Comment by ly3too** [comment]
set GOARCH to amd64 can compile inded, but panic at init
