### ISSUE TITLE
registerFunction参数不同平台不一致

### ISSUE THREAD

**Issue by kissy-xxy** [bytedance/sonic#290]
docker build --platform linux/amd64 时候报错
=> => # /go/pkg/mod/github.com/bytedance/sonic@v1.3.0/internal/loader/loader.go:47:50: too many arguments in call to registerFunction
 => => # have (string, uintptr, uintptr, int, int, uintptr, uintptr, uintptr)
 => => # want (string, uintptr, int, int, uintptr)

**Comment by AsterDY** [comment]
主要是因为你在sonic不支持的环境下才会触发，留下了这个bug也算是b y
