### ISSUE TITLE
Go Report Card result D

### ISSUE THREAD

**Issue by wangkechun** [bytedance/sonic#3]
![image](https://user-images.githubusercontent.com/4022174/120132763-7e9c6f00-c1fd-11eb-88d2-8695b7b10c87.png)

**Comment by wangkechun** [comment]
https://goreportcard.com/report/github.com/bytedance/sonic#gofmt

**Comment by chenzhuoyu** [comment]
Most of the report are code-style "issues", in fact, I consider none of them as "issues". Programs are suppose to be readable by human, not machine.

We will fix those non-code-style issues.

Also, JIT engine is no regular Go code, linting them with regular rules might not be a good idea.
