### ISSUE TITLE
internal\loader\loader.go:28:11: undefined: syscall.MAP_ANON

### ISSUE THREAD

**Issue by overstarry** [bytedance/sonic#30]
D:\go\pkg\mod\github.com\bytedance\sonic@v0.0.0-20210624083732-e9b6634cac5a\internal\loader\loader.go:28:11: undefined: syscall.MAP_ANON
D:\go\pkg\mod\github.com\bytedance\sonic@v0.0.0-20210624083732-e9b6634cac5a\internal\loader\loader.go:28:31: undefined: syscall.MAP_PRIVATE
D:\go\pkg\mod\github.com\bytedance\sonic@v0.0.0-20210624083732-e9b6634cac5a\internal\loader\loader.go:29:11: undefined: syscall.PROT_READ
D:\go\pkg\mod\github.com\bytedance\sonic@v0.0.0-20210624083732-e9b6634cac5a\internal\loader\loader.go:29:31: undefined: syscall.PROT_EXEC
D:\go\pkg\mod\github.com\bytedance\sonic@v0.0.0-20210624083732-e9b6634cac5a\internal\loader\loader.go:30:11: undefined: syscall.PROT_READ
D:\go\pkg\mod\github.com\bytedance\sonic@v0.0.0-20210624083732-e9b6634cac5a\internal\loader\loader.go:30:31: undefined: syscall.PROT_WRITE
D:\go\pkg\mod\github.com\bytedance\sonic@v0.0.0-20210624083732-e9b6634cac5a\internal\loader\loader.go:59:19: undefined: syscall.RawSyscall6
D:\go\pkg\mod\github.com\bytedance\sonic@v0.0.0-20210624083732-e9b6634cac5a\internal\loader\loader.go:59:39: undefined: syscall.SYS_MMAP
D:\go\pkg\mod\github.com\bytedance\sonic@v0.0.0-20210624083732-e9b6634cac5a\internal\loader\loader.go:67:21: undefined: syscall.RawSyscall
D:\go\pkg\mod\github.com\bytedance\sonic@v0.0.0-20210624083732-e9b6634cac5a\internal\loader\loader.go:67:40: undefined: syscall.SYS_MPROTECT
D:\go\pkg\mod\github.com\bytedance\sonic@v0.0.0-20210624083732-e9b6634cac5a\internal\loader\loader.go:67:40: too many errors

**Comment by AsterDY** [comment]
Only go1.15 and go1.16 get supported now

**Comment by overstarry** [comment]
go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\overstarry\AppData\Local\go-build
set GOENV=C:\Users\overstarry\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,https://goproxy.io,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\go\src\awesomeTest\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFL

**Comment by overstarry** [comment]
是不是不支持windows,go version go1.16.3 windows/amd64

**Comment by AsterDY** [comment]
Yes. Linux/darwin OS is required

**Comment by overstarry** [comment]
ok
