### ISSUE TITLE
Error while importing github.com/bytedance/sonic/decoder

### ISSUE THREAD

**Issue by thesolotraveller** [bytedance/sonic#300]
I am trying to install `github.com/bytedance/sonic v1.4.0` on my Macbook which is having M1 Pro processor

Getting this error below:

`error while importing github.com/bytedance/sonic/decoder: build constraints exclude all Go files in /Users/mohitgupta/go/src/github.com/mycompany/myrepository/vendor/github.com/bytedance/sonic/internal/native`

Any suggestions on how to fix this?

**Comment by ii64** [comment]
No native support yet, please see #172, https://github.com/bytedance/sonic/issues/172#issuecomment-1172073548
Check https://github.com/bytedance/sonic/issues/172#issuecomment-1222253710, see if it resolve the problem.

**Comment by AsterDY** [comment]
you are using go env `ARCH=arm64` of `decoder` package directly. You should use `sonic.API.NewDecoder` instead
