### ISSUE TITLE
Proposal: add none implement for `Pretouch` under arm arch.

### ISSUE THREAD

**Issue by xiekeyi98** [bytedance/sonic#301]
Now functions like `Pretouch` only compile under amd64.
https://github.com/bytedance/sonic/blob/main/sonic.go#L1 

How about using the conditional compilation to provide a none implement under arm64?
(I think it will be helpful for some users to develop their code which not use conditional compilation to use `Pretouch` feature under Apple M1. 

It will be  like

```Golang
build !amd64


// None Implement for !amd64
func Pretouch(vt reflect.Type, opts ...option.CompileOption) error {
	 return nil.
}
```

**Comment by AsterDY** [comment]
Thanks for the feedback. We will add it on our next version

**Comment by xiekeyi98** [comment]
If you accept this change, I was wondering would you mind let me have a try？
