### ISSUE TITLE
Mac M1 芯片, 运行报错

### ISSUE THREAD

**Issue by peakrock** [bytedance/sonic#308]
go mod tidy
go build 全部报错
UT 都没法debug 只能修改 GOARCH=“amd64” 能勉强运行。
报错log ：

 ```
 imports github.com/bytedance/sonic/ast
        imports github.com/bytedance/sonic/internal/native: build constraints exclude all Go files in /Users/bytedance/work/pkg/mod/github.com/bytedance/sonic@v1.5.0/internal/native

```
希望能快点兼容M1 芯片

**Comment by doctormin** [comment]
可以先检查一下是不是GO本身装错了
`go version`
- 应该显示`darwin/arm64`

**Comment by li-jin-gou** [comment]
> 可以先检查一下是不是GO本身装错了 `go version`
> 
> * 应该显示`darwin/arm64`

:thumbsup:

**Comment by peakrock** [comment]
没有装错，
go version go1.18.3 darwin/arm64

**Comment by BaiZe1998** [comment]
`github.com/bytedance/sonic/sonic.go`文件中，首行注释为 -> // +build amd64
