### ISSUE TITLE
请问现在有版本可以支持linux arm64吗？急啊，最近像上arm机器啊

### ISSUE THREAD

**Issue by lxj15398019970** [bytedance/sonic#326]
请问现在有版本可以支持linux arm64吗？急啊，最近像上arm机器啊

**Comment by liuq19** [comment]
sonic 支持 linux arm64 需要等待v2版本，暂时没有排期..  v2版本亟需熟悉 arm 的同学一起支持~

**Comment by piedro** [comment]
> 请问现在有版本可以支持linux arm64吗？急啊，最近像上arm机器啊

老板 搞个 Arm commiter

**Comment by xiaoxiaojushi-ivan** [comment]
我们也在做ARM改造，期望尽快出V2版本

**Comment by shangyaqi** [comment]
我们也想做ARM改造，期待尽快出V2版本

**Comment by shaoyun** [comment]
要上ARM了，期待V2支持
