### ISSUE TITLE
 unsupport cpu panic 

### ISSUE THREAD

**Issue by iwanzhang** [bytedance/sonic#333]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/105045937/204079013-ae1b73bd-f6b2-41e4-a4c5-784e33307ac7.png">
<img width="637" alt="image" src="https://user-images.githubusercontent.com/105045937/204079018-f6e4a4d6-6290-4d52-98fd-da9f8559eb45.png">

**Comment by ii64** [comment]
What's the available CPU flags?

**Comment by jihonghe** [comment]
![image](https://user-images.githubusercontent.com/79737955/204704084-534383c0-ad8f-43ee-ae19-651dd0da3022.png)
今天在CPU E5645上刚爆出这个问题，我引入的sonic...

**Comment by ii64** [comment]
查看 /proc/cpuinfo 如果 `avx2`，`avx`，或 `sse4_1` 存在最。新版本的 sonic 使用 `sse` 作为后备

**Comment by iwanzhang** [comment]
存在

**Comment by chenzhuoyu** [comment]
@iwanzhang cat /proc/cpuinfo | grep flags

**Comment by iwanzhang** [comment]
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology eagerfpu pni cx16 x2apic aes hypervisor lahf_lm

**Comment by liuq19** [comment]
目前使用的 sonic 版本是多少？可以 使用 sonic master 分支，目前已经最低支持 sse 指令了。

**Comment by iwanzhang** [comment]
最新版tag
