### ISSUE TITLE
github.com/bytedance/sonic/internal/native/dispatch_amd64.s:22: undefined reference to `github.com/bytedance/sonic/internal/cpu.HasAVX2'

### ISSUE THREAD

**Issue by wittam** [bytedance/sonic#334]
golang 编译报错：github.com/bytedance/sonic/internal/native/dispatch_amd64.s:22: undefined reference to `github.com/bytedance/sonic/internal/cpu.HasAVX2'
![image](https://user-images.githubusercontent.com/81098845/204215827-955d76ca-d171-4f1a-b115-2ea0c0d5ba5a.png)

**Comment by liuq19** [comment]
what is your CPU arch?

**Comment by wittam** [comment]
Linux version 4.14.81.bm.15-amd64 (root@runner-086f5a3f-project-63-concurrent-0) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)) #1 SMP Debian 4.14.81.bm.15 Sun Sep 8 05:02:31 UTC 2019

**Comment by liuq19** [comment]
> golang 编译报错：github.com/bytedance/sonic/internal/native/dispatch_amd64.s:22: undefined reference to `github.com/bytedance/sonic/internal/cpu.HasAVX2' ![image](https://user-images.githubusercontent.com/81098845/204215827-955d76ca-d171-4f1a-b115-2ea0c0d5ba5a.png)

are you using go vendor here? If yes, you can try to replace all `CMPB github·com∕bytedance∕sonic∕internal∕cpu·HasAVX2(SB), $0` with`CMPB {your vendor path}∕sonic∕internal∕cpu·HasAVX2(SB), $0` in `[sonic](https://github.com/bytedance/sonic)/[internal](https://github.com/bytedance/sonic/tree/main/internal)/[native](https://github.com/bytedance/sonic/tree/main/internal/native)/dispatch_amd64.s`.

**Comment by chenzhuoyu** [comment]
@wittam Sonic 不支持 vendor，如果用到了 vendor 可能会出现问题，请尽可能使用 go mod
