### ISSUE TITLE
failed unmarshal json string with case sensitived tag

### ISSUE THREAD

**Issue by cdpzyafk** [bytedance/sonic#340]
`type AutoGenerated struct {
	W bool        `json:"w"``
}
str := `{"w": true, "W": 1499405658657}`

// yield error when call following 
// sonic.Unmarshal
// sonic.ConfigStd.Unmarshal
// sonic.ConfigFastest.Unmarshal
`

maybe provide case sensitive option in config?

`

**Comment by liuq19** [comment]
use sonic 1.6.0 or above
