### ISSUE TITLE
在sonic包里重新导出NewStreamEncoder和NewStreamDecoder

### ISSUE THREAD

**Issue by trim21** [bytedance/sonic#344]
类似 `json.NewDecoder` 和 `json.NewEncoder`

**Comment by AsterDY** [comment]
https://github.com/bytedance/sonic/blob/main/api.go#L106 这个不就是吗

**Comment by trim21** [comment]
> https://github.com/bytedance/sonic/blob/main/api.go#L106 这个不就是吗

类似 sonic.NewDecoder ，这样在迁移的时候直接把代码中原来的json换成sonic就可以了🤔

**Comment by AsterDY** [comment]
就多写一行代码的事，实在不行你可以自己写个util包封一下
