### ISSUE TITLE
How to compatibility jsonpb ?

### ISSUE THREAD

**Issue by limpo1989** [bytedance/sonic#347]
> https://developers.google.com/protocol-buffers/docs/proto3#json
<html>
<body>

proto3 | JSON | JSON example | Notes
-- | -- | -- | --
int64, fixed64, uint64 | string | "1", "-10" | JSON value will be a decimal string. Either numbers or strings are accepted.
-- | -- | -- | --

</body>
</html>

protobuf:
```protobuf
message Class {
  optional int64 value1 = 1;
  repeated int64 values2 = 2;
  optional uint64 value3 = 3;
  repeated uint64 values4 = 4;
}
```

example:
```go
class := &Class{
  Value1:  proto.Int64(9007199254740993),
  Values2: []int64{9007199254740993, 9007199254740994, 9007199254740995},
  Value3:  proto.Uint64(9007199254740993),
  Values4: []uint64{9007199254740993, 9007199254740994, 9007199254740995},
}

m := &jsonpb.Marshaler{
	OrigName:     true,
}

data, _ := m.MarshalToString(class)
fmt.Println("jsonpb(marshall): ", data)

var newClass Class
_ = jsonpb.UnmarshalString(data, &newClass)
fmt.Println("jsonpb(unmarshall): ", newClass.String() == class.String())
```

output:
```
jsonpb(marshall):  {"value1":"9007199254740993","values2":["9007199254740993","9007199254740994","9007199254740995"],"value3":"9007199254740993","values4":["9007199254740993","9007199254740994","9007199254740995"]}
jsonpb(unmarshall):  true
```

**Comment by AsterDY** [comment]
`TypeDecoder|Encoder` is not supportable because low-level implementation is totally different. If your primary need is only convenience instead of performance, you can still use `json-iterator`. If not, you should implement `json.Marshaler|Unmarshaler` interface for specific type (instead of kind).

**Comment by limpo1989** [comment]
@AsterDY  Javascript/Lua number type represents real (double-precision floating-point) numbers,  This means the largest number the JS/Lua can represent without losing prescision is 2^52.

Maybe sonic provide like <code>Int64AsString</code> / <code>Int64FromString</code> options for encoder/decoder to change default behavior ?

**Comment by AsterDY** [comment]
![image](https://user-images.githubusercontent.com/22593627/212473447-ddbeb9db-89f7-4c2a-918e-55d923bbfd5a.png)
this is supported by sonic

**Comment by limpo1989** [comment]
@AsterDY The scheme is generated by protoc and no provide option to changed the json tags in currently.
```go
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: class.proto

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Class struct {
	Value1               *int64            `protobuf:"varint,1,opt,name=value1" json:"value1,omitempty"`
	Values2              []int64           `protobuf:"varint,2,rep,name=values2" json:"values2,omitempty"`
	Value3               *uint64           `protobuf:"varint,3,opt,name=value3" json:"value3,omitempty"`
	Values4              []uint64          `protobuf:"varint,4,rep,name=values4" json:"values4,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}
```

**Comment by AndrewHuangMiao** [comment]
@limpo1989 hi, could u tell me your solution of this problem? I have met the same issue

**Comment by limpo1989** [comment]
> [json-iterator](https://github.com/json-iterator/go) provide `RegisterTypeDecoder/RegisterTypeEncoder` register TypeDecoder/TypeEncoder for a type, like this:
> 
> ```go
> func EnableCompatibilityJsonpb() {
> 
> 	jsoniter.RegisterTypeDecoderFunc("uint64", func(ptr unsafe.Pointer, iter *jsoniter.Iterator) {
> 		if strVal := iter.ReadAny().ToString(); "" != strVal {
> 			val, err := strconv.ParseUint(strVal, 10, 64)
> 			if nil != err {
> 				iter.ReportError("decodeUint64FromString", err.Error())
> 				return
> 			}
> 			var intPtr = (*uint64)(ptr)
> 			*intPtr = val
> 		}
> 	})
> 
> 	jsoniter.RegisterTypeEncoderFunc("uint64", func(ptr unsafe.Pointer, stream *jsoniter.Stream) {
> 		var intPtr = (*uint64)(ptr)
> 		stream.WriteString(strconv.FormatUint(*intPtr, 10))
> 	}, func(pointer unsafe.Pointer) bool {
> 		ptr := (*uint64)(pointer)
> 		return 0 == *ptr
> 	})
> 
> 	jsoniter.RegisterTypeDecoderFunc("int64", func(ptr unsafe.Pointer, iter *jsoniter.Iterator) {
> 		if strVal := iter.ReadAny().ToString(); "" != strVal {
> 			val, err := strconv.ParseInt(strVal, 10, 64)
> 			if nil != err {
> 				iter.ReportError("decodeInt64FromString", err.Error())
> 				return
> 			}
> 			var intPtr = (*int64)(ptr)
> 			*intPtr = val
> 		}
> 	})
> 
> 	jsoniter.RegisterTypeEncoderFunc("int64", func(ptr unsafe.Pointer, stream *jsoniter.Stream) {
> 		var intPtr = (*int64)(ptr)
> 		stream.WriteString(strconv.FormatInt(*intPtr, 10))
> 	}, func(pointer unsafe.Pointer) bool {
> 		ptr := (*int64)(pointer)
> 		return 0 == *ptr
> 	})
> }
> ```

@AndrewHuangMiao This problem cannot be solved effectively in `sonic`, so we continue to use `json-iterator`
