### ISSUE TITLE
sonic node can't get length by node.Len() method

### ISSUE THREAD

**Issue by haifeiWu** [bytedance/sonic#349]
if Len used before len like this
![image](https://user-images.githubusercontent.com/18307810/211993329-7b245b41-cec9-429d-ba20-b0734e745a96.png)

len used before Len like this
![image](https://user-images.githubusercontent.com/18307810/211993082-e982714d-e64e-49c9-8989-59adae15a6e0.png)

**Comment by AsterDY** [comment]
see the API comment of `Len()`
