### ISSUE TITLE
bug: go test panic in /encoder and /decoder

### ISSUE THREAD

**Issue by wymli** [bytedance/sonic#35]
## overview
The unit test panicked in /encoder and /decoder, 
saying :
```
# github.com/goccy/go-json/internal/encoder/vm 
fatal error: runtime: out of memory
```
## go version
go version go1.16 linux/amd64

## go env
```sh
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/liwm29/gopath/bin"
GOCACHE="/home/liwm29/.cache/go-build"
GOENV="/home/liwm29/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/liwm29/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/liwm29/gopath"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/liwm29/sonic_raw/sonic/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1917513849=/tmp/go-build -gno-record-gcc-switches"
```

## what happened
```sh
[liwm29@VM-12-11-centos sonic]$ go test ./...
ok      github.com/bytedance/sonic      4.103s
ok      github.com/bytedance/sonic/ast  0.006s
# github.com/goccy/go-json/internal/encoder/vm
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xcac67f, 0x16)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sysMap(0xc030000000, 0xc000000, 0x11e7b90)
        /usr/local/go/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x11c8bc0, 0xa000000, 0x42bcf7, 0x11c8bc8)
        /usr/local/go/src/runtime/malloc.go:729 +0x1e5
runtime.(*mheap).grow(0x11c8bc0, 0x4ef7, 0x0)
        /usr/local/go/src/runtime/mheap.go:1346 +0x85
runtime.(*mheap).allocSpan(0x11c8bc0, 0x4ef7, 0x440100, 0x7f1fa3d21688)
        /usr/local/go/src/runtime/mheap.go:1173 +0x609
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:910 +0x59
runtime.systemstack(0x46d334)
        /usr/local/go/src/runtime/asm_amd64.s:379 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1246

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:339 fp=0xc00286cac0 sp=0xc00286cab8 pc=0x46d460
runtime.(*mheap).alloc(0x11c8bc0, 0x4ef7, 0xc002860001, 0xc00458c000)
        /usr/local/go/src/runtime/mheap.go:904 +0x85 fp=0xc00286cb10 sp=0xc00286cac0 pc=0x4279a5
runtime.(*mcache).allocLarge(0x7f1fcac23108, 0x9dee000, 0xc002be0100, 0x7f1fa3d21688)
        /usr/local/go/src/runtime/mcache.go:224 +0x97 fp=0xc00286cb68 sp=0xc00286cb10 pc=0x418017
runtime.mallocgc(0x9dee000, 0x0, 0x0, 0xc002be2000)
        /usr/local/go/src/runtime/malloc.go:1078 +0x925 fp=0xc00286cbf0 sp=0xc00286cb68 pc=0x40de65
runtime.growslice(0xc686a0, 0xc025b74000, 0x7e5800, 0x7e5800, 0x7e5801, 0x1122970, 0x1, 0xc0)
        /usr/local/go/src/runtime/slice.go:224 +0x154 fp=0xc00286cc58 sp=0xc00286cbf0 pc=0x44fcd4
cmd/compile/internal/ssa.(*debugState).appendLiveSlot(...)
        /usr/local/go/src/cmd/compile/internal/ssa/debug.go:290
cmd/compile/internal/ssa.(*debugState).liveness(0xc001ccd660, 0xc0014b33b0, 0xc0032bb030, 0xc0047a58d8)
        /usr/local/go/src/cmd/compile/internal/ssa/debug.go:512 +0x7e5 fp=0xc00286ce58 sp=0xc00286cc58 pc=0x6705a5
cmd/compile/internal/ssa.BuildFuncDebug(0xc0000fa000, 0xc0018c51e0, 0xc0041be300, 0xcc81f8, 0x6a9)
        /usr/local/go/src/cmd/compile/internal/ssa/debug.go:436 +0xa65 fp=0xc00286d0d0 sp=0xc00286ce58 pc=0x66f345
cmd/compile/internal/gc.genssa(0xc0018c51e0, 0xc004c62000)
        /usr/local/go/src/cmd/compile/internal/gc/ssa.go:6527 +0x28ac fp=0xc00286d5b0 sp=0xc00286d0d0 pc=0xb437ec
cmd/compile/internal/gc.compileSSA(0xc0000e5e40, 0x0)
        /usr/local/go/src/cmd/compile/internal/gc/pgen.go:329 +0x3a5 fp=0xc00286d690 sp=0xc00286d5b0 pc=0xad7685
cmd/compile/internal/gc.compile(0xc0000e5e40)
        /usr/local/go/src/cmd/compile/internal/gc/pgen.go:277 +0x39e fp=0xc00286d708 sp=0xc00286d690 pc=0xad711e
cmd/compile/internal/gc.funccompile(0xc0000e5e40)
        /usr/local/go/src/cmd/compile/internal/gc/pgen.go:220 +0xc5 fp=0xc00286d760 sp=0xc00286d708 pc=0xad6c65
cmd/compile/internal/gc.Main(0xcc7d20)
        /usr/local/go/src/cmd/compile/internal/gc/main.go:762 +0x3525 fp=0xc00286df10 sp=0xc00286d760 pc=0xaabbe5
main.main()
        /usr/local/go/src/cmd/compile/main.go:52 +0xb1 fp=0xc00286df88 sp=0xc00286df10 pc=0xbf90d1
runtime.main()
        /usr/local/go/src/runtime/proc.go:225 +0x256 fp=0xc00286dfe0 sp=0xc00286df88 pc=0x439d76
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00286dfe8 sp=0xc00286dfe0 pc=0x46f161
FAIL    github.com/bytedance/sonic/decoder [build failed]
FAIL    github.com/bytedance/sonic/encoder [build failed]
ok      github.com/bytedance/sonic/internal/caching     0.002s
?       github.com/bytedance/sonic/internal/cpu [no test files]
ok      github.com/bytedance/sonic/internal/jit 0.004s
ok      github.com/bytedance/sonic/internal/loader      0.003s
?       github.com/bytedance/sonic/internal/native      [no test files]
ok      github.com/bytedance/sonic/internal/native/avx  0.006s
ok      github.com/bytedance/sonic/internal/native/avx2 0.006s
?       github.com/bytedance/sonic/internal/native/types        [no test files]
ok      github.com/bytedance/sonic/internal/resolver    0.002s
?       github.com/bytedance/sonic/internal/rt  [no test files]
?       github.com/bytedance/sonic/unquote      [no test files]
FAIL
```
## other
i have changed nothing, except cloning and cd /sonic and run `go test ./...`

**Comment by AsterDY** [comment]
Not reproduce on my PC. Maybe ask help for @goccy ?

**Comment by wymli** [comment]
[liwm29@VM-12-11-centos test_sonic]$ uname -a
Linux VM-12-11-centos 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

the machine is a `tencent cloud server`      @goccy

**Comment by goccy** [comment]
Perhaps this is an error caused by a very low memory on the server being built.
I have confirmed that it can be compiled with at least 600MB ( FYI: https://github.com/goccy/go-json/blob/master/docker-compose.yml#L10 ). Check the memory of the server .

**Comment by wymli** [comment]
[liwm29@VM-12-11-centos sonic]$ cat /proc/meminfo 
MemTotal:        1882020 kB
MemFree:          606568 kB
MemAvailable:     859404 kB
Buffers:           14476 kB
Cached:           362404 kB
SwapCached:            0 kB
Active:           878820 kB
Inactive:         273936 kB
Active(anon):     782712 kB
Inactive(anon):      276 kB
Active(file):      96108 kB
Inactive(file):   273660 kB
Unevictable:        7936 kB
Mlocked:            7936 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               136 kB
Writeback:             0 kB
AnonPages:        783864 kB
Mapped:            56000 kB
Shmem:               684 kB
Slab:              46684 kB
SReclaimable:      28460 kB
SUnreclaim:        18224 kB
KernelStack:        4528 kB
PageTables:        15116 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      941008 kB
Committed_AS:    2708884 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        9292 kB
VmallocChunk:   34359726588 kB
Percpu:              164 kB
HardwareCorrupted:     0 kB
AnonHugePages:     26624 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       63352 kB
DirectMap2M:     2033664 kB
DirectMap1G:           0 kB

**Comment by goccy** [comment]
There seems to be a relationship. It actually compiles another library besides go-json at the same time,
so you may need a little more memory.

**Comment by wymli** [comment]
Actually, `MemAvailable: 859404 kB` is the mem a process can really get without swapping. 
>>> 859404 / 1024.
839.26171875
maybe other pkgs won't occupy more than 200M?

ok, i will try it later on a machine with larger mem.

**Comment by wymli** [comment]
Well, in my wsl, it works.
Thanks a lot

liwm29@wymli-NB1:/mnt/d/app/sonic$ go test -count=1 ./...
ok      github.com/bytedance/sonic      3.119s
ok      github.com/bytedance/sonic/ast  0.024s
ok      github.com/bytedance/sonic/decoder      0.282s
ok      github.com/bytedance/sonic/encoder      0.265s
ok      github.com/bytedance/sonic/internal/caching     0.027s
?       github.com/bytedance/sonic/internal/cpu [no test files]
ok      github.com/bytedance/sonic/internal/jit 0.019s
ok      github.com/bytedance/sonic/internal/loader      0.026s
?       github.com/bytedance/sonic/internal/native      [no test files]
ok      github.com/bytedance/sonic/internal/native/avx  0.013s
ok      github.com/bytedance/sonic/internal/native/avx2 0.011s
?       github.com/bytedance/sonic/internal/native/types        [no test files]
ok      github.com/bytedance/sonic/internal/resolver    0.004s
?       github.com/bytedance/sonic/internal/rt  [no test files]
?       github.com/bytedance/sonic/unquote      [no test files]

liwm29@wymli-NB1:/mnt/c/WINDOWS/system32$ cat /proc/meminfo
MemTotal:        6399360 kB
MemFree:         6285696 kB
MemAvailable:    6180448 kB
