### ISSUE TITLE
sonic does not support go1.20

### ISSUE THREAD

**Issue by ivanlebron** [bytedance/sonic#355]
# github.com/bytedance/sonic/internal/loader
../../../go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/funcdata.go:27:22: undefined: _ModuleData
../../../go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/funcdata.go:30:27: undefined: _ModuleData
../../../go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/funcdata.go:41:6: undefined: _Func
../../../go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/funcdata.go:42:12: undefined: _ModuleData
../../../go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/funcdata.go:53:16: undefined: _ModuleData
../../../go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/funcdata.go:79:26: undefined: _ModuleData
../../../go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/funcdata_invalid.go:23:6: panic("Unsupported Go version. Supported versions are: 1.15, 1.16, 1.17, 1.18, 1.19") (no value) used as value
../../../go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/loader.go:47:50: too many arguments in call to registerFunction
	have (string, uintptr, uintptr, int, int, uintptr, uintptr, uintptr)
	want (string, uintptr, int, int, uintptr)

**Comment by ii64** [comment]
There's on going implementation to support go120:
https://github.com/bytedance/sonic/pull/354 (merge feat/go120 into main)
https://github.com/bytedance/sonic/tree/feat/go120

**Comment by AsterDY** [comment]
WIP

**Comment by kataras** [comment]
I can confirm that too for https://github.com/kataras/iris

```
# github.com/bytedance/sonic/internal/loader
/go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/funcdata.go:27:22: undefined: _ModuleData
/go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/funcdata.go:30:27: undefined: _ModuleData
/go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/funcdata.go:41:6: undefined: _Func
/go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/funcdata.go:42:12: undefined: _ModuleData
/go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/funcdata.go:53:16: undefined: _ModuleData
/go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/funcdata.go:79:26: undefined: _ModuleData
/go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/funcdata_invalid.go:23:6: panic("Unsupported Go version. Supported versions are: 1.15, 1.16, 1.17, 1.18, 1.19") (no value) used as value
/go/pkg/mod/github.com/bytedance/sonic@v1.7.0/internal/loader/loader.go:47:50: too many arguments in call to registerFunction
	have (string, uintptr, uintptr, int, int, uintptr, uintptr, uintptr)
	want (string, uintptr, int, int, uintptr)
The command '/bin/sh -c go install -ldflags="-s -w"' returned a non-zero code: 1
```

**Comment by redghc** [comment]
At the moment I recommend you use a specific version of go:
https://go.dev/doc/manage-install


```
$ go install golang.org/dl/go1.19.5@latest
$ go1.19.5 download

$ cd /your/project/path
$ go1.19.5 run .
```

**Comment by hiqsociety** [comment]
waiting for this too.
wonder when the eta of merge is?

**Comment by ivanlebron** [comment]
does the new version have a schedule？

**Comment by AsterDY** [comment]
#354 resloved

**Comment by wxmeng04** [comment]
> #354 resloved
```
go test -benchmem --bench=Benchmark benchmark_test.go
# github.com/bytedance/sonic/internal/loader
...
..\..\..\go\pkg\mod\github.com\bytedance\sonic@v1.7.0\internal\loader\funcdata_invalid.go:23:6: panic("Unsupported Go version. Supported versions are: 1.15, 1.16, 1.17, 1.18, 1.19") (no value) used as value
...
```
while .mod file indicate a reference to `require github.com/bytedance/sonic v1.8.8`, the build step still refers to version 1.7.0
