### ISSUE TITLE
MarshalJSONToWriter support

### ISSUE THREAD

**Issue by strokovok** [bytedance/sonic#356]
Hi! I'm wondering if there's any ability to define a custom type encoding function like `MarshalJSONToWriter(w io.Writer) error` or `AppendJson(dst []byte) ([]byte, error)` in order to write directly to output to avoid lots of memory copying

**Comment by hyperion-cs** [comment]
Yes, I also prefer to operate with bits **directly**. It wouldn't hurt...

**Comment by AsterDY** [comment]
exposing `writer` or `*byte[]` is extremely unsafe, and we can't do json validate (https://github.com/bytedance/sonic/blob/main/encoder/primitives.go#L89) therefore.

**Comment by strokovok** [comment]
@AsterDY 
Why is it unsafe? There's a very easy way to allow appending without access to the original value.
Furthermore, it's also very easy to `compact` and `Validate` newly appended data.
Let me show you:

```go
type JsonAppendMarshaler interface {
	AppendJSON(io.Writer) error
}

type appendWriter struct {
	data []byte
}

func (aw *appendWriter) Write(data []byte) (int, error) {
	aw.data = append(aw.data, data...)
	return len(data), nil
}

func encodeJsonAppendMarshaler(buf *[]byte, val JsonAppendMarshaler, opt Options) error {
	aw := &appendWriter{data: *buf}
	if err := val.AppendJSON(aw); err != nil {
		return err
	} else {
		appended := aw.data[len(*buf):]
		if opt & CompactMarshaler != 0 {
			return compact(buf, appended)
		}
		if ok, s := Valid(appended); !ok {
			return error_marshaler(appended, s)
		}
		*buf = aw.data
		return nil
	}
}
```

Do you see any flaws in there?
