### ISSUE TITLE
Propose: add api to tell whether the implementation is std fallback

### ISSUE THREAD

**Issue by jxskiss** [bytedance/sonic#367]
As titled, sonic is used for high performance use-case, with an API to tell the implementation is std fallback, user may choose to switch to other implementation (e,g, jsoniter) when sonic is not supported for the platofrm or go version.

**Comment by jxskiss** [comment]
For now there is a workaround to check the underlying impl, by marshaling a struct that implements json.Marshaller which panics, then checking the stacktrace. But it is a little tricky, maybe providing a method is a better way.

**Comment by AsterDY** [comment]
sonic uses compiling constraints (https://github.com/bytedance/sonic/blob/main/sonic.go#L1) to decide if fallback. You can use the same method as well

**Comment by jxskiss** [comment]
> sonic uses compiling constraints (https://github.com/bytedance/sonic/blob/main/sonic.go#L1) to decide if fallback. You can use the same method as well

是的，条件编译可以解决编译问题，但是有两个问题，1) 编译条件跟 sonic 耦合在了一起，依赖 sonic 的报需要跟着 sonic 一起更新编译条件才行; 2) 如果是一个相对底层的库依赖了 sonic, 在 sonic 不支持的平台上或者 go 新版本发布后 sonic 还没有更新时，会降级到 "encoding/json", 程序仍然可以编译但是性能会劣化很多。
如果提供一个 api 的话，上层应用可以加一层适配，在 sonic 不支持时，可以选择 fallback  到其他的 json 库。
