### ISSUE TITLE
UnmarshalJSON死循环

### ISSUE THREAD

**Issue by toolin-fox** [bytedance/sonic#379]
第一次提issues，可能不太规范
类似代码如下：
```
func (t *UserData) UnmarshalJSON(buf []byte) (err error) {
    type alice *UserData //新的类型，擦除原类型
    return sonic.Unmarshal(buf, alice(t)) //死循环(*UserData) UnmarshalJSON
    //return json.Unmarshal(buf, alice(t)) //标准库不会
}
```
标准库在使用 alice 定义新类型之后，是可以处理这个场景。同类jsoniter库同样没有办法处理

**Comment by liuq19** [comment]
感谢反馈，请提供可复现的输入数据和最小化代码

**Comment by toolin-fox** [comment]
> 感谢反馈，请提供可复现的输入数据和最小化代码

type Foo struct {
	Name string
}

//UnmarshalJSON Unmarshaler
func (f *Foo) UnmarshalJSON(data []byte) error {
	//do something
	fmt.Println("myself Unmarshal")
	type alice *Foo
	//return json.Unmarshal(data, alice(f))  // encoding/json do once 标准库执行一次
	return sonic.Unmarshal(data, alice(f)) // always loop: sonic.Unmarshal->*Foo.UnmarshalJSON->sonic.Unmarshal
}
func main() {
	f := &Foo{}
	json.Unmarshal([]byte(`{}`), f)
}

**Comment by liuq19** [comment]
已经复现，我们讨论下，近期会解决

**Comment by toolin-fox** [comment]
居然解决了，引入了一个性能吃紧的服务 提升非常大。感谢
