### ISSUE TITLE
macbook pro m1芯片编译失败

### ISSUE THREAD

**Issue by SCUT-FMS** [bytedance/sonic#384]
当我在m1芯片上便衣的时候出现以下错误
imports github.com/bytedance/sonic/internal/native: build constraints exclude all Go files in /Users/bytedance/go/pkg/mod/github.com/bytedance/sonic@v1.0.1-0.20220118062719-f8efc2f6e70f/internal/native

go版本为1.17.3 
有建议的解决方法吗

**Comment by liuq19** [comment]
升级sonic到最新版

**Comment by SCUT-FMS** [comment]
> 升级sonic到最新版

升级完需要做些什么配置吗 我升级完还是会报错 我自己的项目是不需要用到sonic的 是我依赖的包里面用到了sonic

**Comment by SCUT-FMS** [comment]
> 升级sonic到最新版

![Uploading 截屏2023-03-16 16.01.27.png…]()

**Comment by SCUT-FMS** [comment]
> 升级sonic到最新版

<img width="1439" alt="截屏2023-03-16 16 01 27" src="https://user-images.githubusercontent.com/49604423/225552482-8ffc2325-631a-472e-96ac-4aab0bba6b77.png">

**Comment by SCUT-FMS** [comment]
> 升级sonic到最新版

go version go1.17.13 darwin/arm64

**Comment by liuq19** [comment]
> > 升级sonic到最新版
> 
> <img alt="截屏2023-03-16 16 01 27" width="1439" src="https://user-images.githubusercontent.com/49604423/225552482-8ffc2325-631a-472e-96ac-4aab0bba6b77.png">

这里是使用了 sonic/encoder 包里面的api，你换成对应的 sonic.xxx api就好啦。目前encoder 里面的api还不支持 fallback。

**Comment by liuq19** [comment]
看能否推动第三方包改一下
