### ISSUE TITLE
It seems sonic has memory leak issue on 1.8.5

### ISSUE THREAD

**Issue by mm2175** [bytedance/sonic#395]
pyroscope mem chart:

![image](https://user-images.githubusercontent.com/30251661/228730147-37e61a34-8c88-4cfd-a5bc-ae28f54ecdf7.png)

grafana memory usage
![image](https://user-images.githubusercontent.com/30251661/228730176-dff2d17c-cf9b-4557-a7dc-04e801cd154d.png)

pyroscope diff
![image](https://user-images.githubusercontent.com/30251661/228730290-dd6f7226-8b1b-4f88-b5a7-cd229dcfd3c1.png)

**Comment by AsterDY** [comment]
please provide more specific `pprof` records ( in-use heap)  and minized test codes

**Comment by mm2175** [comment]
The problem haven't occur after I post this issue, I guess its a rare case.

**Comment by sishui** [comment]
We have also encountered in the project (1.8x several versions have tried and encountered), grafana monitoring shows normal, but 10-15 days will os memory alarm, without changing any business code, replaced with std-json, run for two weeks without problems for the time being, do not know if we use sonic way is not right

**Comment by AsterDY** [comment]
maybe related to `decoder.CopyString` as far as know, you can try it

**Comment by eiguleo** [comment]
![image](https://github.com/bytedance/sonic/assets/21966660/b6f3640f-e53c-4fd7-b931-ea2914382d02)
same

**Comment by AsterDY** [comment]
171MB doesn't look so bad?

**Comment by eiguleo** [comment]
> 171MB doesn't look so bad?

the reason is not in sonic , i forgot closing the groutine that consume data from sonic :)
