### ISSUE TITLE
1.8.7bug

### ISSUE THREAD

**Issue by Nyx2022** [bytedance/sonic#397]
我同样的代码，使用sonic 1.8.7反序列化的时候会报以下错误：
json: cannot unmarshal  into Go value of type func() (io.ReadCloser, error)

但是1.8.6不会，望修复

**Comment by liuq19** [comment]
能否提供最小化可复现的例子

**Comment by Nyx2022** [comment]
> 能否提供最小化可复现的例子

不太方便提供，应该是我反序列化到的struct中的某个字段的类型导致的

**Comment by liuq19** [comment]
可以试下这个分支 fix/recurse_ptr，对应pr https://github.com/bytedance/sonic/pull/400 ， 看能否解决问题

**Comment by Nyx2022** [comment]
> 可以试下这个分支 fix/recurse_ptr，对应pr #400 ， 看能否解决问题

我要怎样修改go.mod文件才能使用这个分支

**Comment by liuq19** [comment]
go get github.com/bytedance/sonic@fix/recurse_ptr 更新依赖的sonic库

**Comment by Nyx2022** [comment]
> 可以试下这个分支 fix/recurse_ptr，对应pr #400 ， 看能否解决问题

还是不行，还是存在这个问题

**Comment by liuq19** [comment]
最好抽离出最小可行化的复现 demo，这样才能高效排查哈

**Comment by chenzhuoyu** [comment]
请提供能复现的测试用例，你的描述过于抽象，我们无法通过你的描述重现问题。
