### ISSUE TITLE
CWE-78 Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')

### ISSUE THREAD

**Issue by lgcmotta** [bytedance/sonic#398]
I use Veracode on my CI/CD. Just got this message:

> CWE-78: Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection'): src/vendor/github.com/bytedance/sonic/bench.py:26

## Description:

This call to `os.system()` contains a command injection flaw. The argument to the function is constructed using user-supplied input. If an attacker is allowed to specify all or part of the command, it may be possible to execute commands on the server with the privileges of the executing process. The level of exposure depends on the effectiveness of input validation routines, if any. Validate all user-supplied input to ensure that it conforms to the expected format, using centralized data validation routines when possible. When using blocklists, be sure that the sanitizing routine performs a sufficient number of iterations to remove all instances of disallowed characters. Most APIs that execute system commands also have a "safe" version of the method that takes an array of strings as input rather than a single string, which protects against some forms of command injection. 

- Severity: Very High
- Confidence: High
- Location: src/vendor/github.com/bytedance/sonic/bench.py:26
- Scanner: Veracode Pipeline Scan

## CWE

- [CWE](https://cwe.mitre.org/data/definitions/78.html)

**Comment by AsterDY** [comment]
just for test, no need to care
