### ISSUE TITLE
CWE-78

### ISSUE THREAD

**Issue by Jardelpz** [bytedance/sonic#399]
Veracode Report a very high vulnerability in file bench.py: Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection') (https://cwe.mitre.org/data/definitions/78.html) 

I believe it is in the run function where the cmd is passed as a parameter and no validation is done before being executed in os.system(), we should use the subprocess in this case

**Comment by ii64** [comment]
Though that's a tooling script, used for benchmark testing and is unrelated to the library. It's not something that accept arbitrary shell command
