### ISSUE TITLE
支持在Tag中设置default值

### ISSUE THREAD

**Issue by Nyx2022** [bytedance/sonic#402]
我知道，golang中对每个类型都有自己的零值，如果json字符串中没有某个字段的话，我不清楚sonic实惠按照零值处理还是可以通过在字段的tag中设置default来指定。如果暂时不支持设置default的话，因为golang的零值不见得每次都适合，建议支持一下，谢谢

**Comment by AsterDY** [comment]
jit不好做，你可以new 对象时候先设置好默认值再传给sonic
