### ISSUE TITLE
Problem building for Linux/ARM (Int overflow) 1.8.7

### ISSUE THREAD

**Issue by Rheisen** [bytedance/sonic#405]
building for linux/arm
github.com/bytedance/sonic/internal/rt
/go/pkg/mod/github.com/bytedance/sonic@v1.8.7/internal/rt/int48.go:25:28: MinInt48 (untyped int constant -140737488355328) overflows int
/go/pkg/mod/github.com/bytedance/sonic@v1.8.7/internal/rt/int48.go:25:44: MaxInt48 (untyped int constant 140737488355327) overflows int

**Comment by liuq19** [comment]
Please provide a minimal reproducible example

**Comment by ii64** [comment]
The issue occurs when trying to compile sonic for 32-bit system where `int` size is less than 48-bits

```
> go env | grep -E "GO(OS|ARCH)"
GOARCH="amd64"
GOOS="linux"
> go build .
> GOARCH=arm64 go build .
> GOARCH=arm go build .
# github.com/bytedance/sonic/internal/rt
/home/ii64/go/pkg/mod/github.com/bytedance/sonic@v1.8.7/internal/rt/int48.go:25:28: MinInt48 (untyped int constant -140737488355328) overflows int
/home/ii64/go/pkg/mod/github.com/bytedance/sonic@v1.8.7/internal/rt/int48.go:25:44: MaxInt48 (untyped int constant 140737488355327) overflows int
```

**Comment by Rheisen** [comment]
Here is a minimal main.go file that will trigger this error when building:

```
package main

import (
	"fmt"

	"github.com/bytedance/sonic"
)

func main() {
	type dataPacket struct {
		Message string  `json:"message"`
		Errors  []error `json:"errors"`
	}

	messagePacket := &dataPacket{
		Message: "hello",
	}

	messagePacketBytes, err := sonic.Marshal(messagePacket)
	if err != nil {
		fmt.Printf("problem creating message packet: %s\n", err)

		return
	}

	fmt.Printf("message packet bytes: %s\n", messagePacketBytes)
}
```


```
GOOS=linux GOARCH=arm go build .
```

**Comment by liuq19** [comment]
> 

Could you provide the architecture information using the "lscpu" command? There may be some issues running it on a 32-bit ARM machine.
