### ISSUE TITLE
windows10 使用sonic库报错#

### ISSUE THREAD

**Issue by Bronya0** [bytedance/sonic#431]
示例代码
```go
package main

import (
	"github.com/bytedance/sonic"
	"os"
)

func main() {
	data, err := os.ReadFile("J:\\search.json")
	if err != nil {
		panic(err)
	}
	comcodeBuckets, err := sonic.Get(data, "aggregations","hahaha1","buckets")
	println(comcodeBuckets.Array())
}

```
报错内容
github.com/bytedance/sonic/internal/rt
J:\Coding\go\pkg\mod\github.com\bytedance\sonic@v1.8.1\internal\rt\int48.go:25:28: MinInt48 (untyped int constant -140737488355328) overflows int
J:\Coding\go\pkg\mod\github.com\bytedance\sonic@v1.8.1\internal\rt\int48.go:25:44: MaxInt48 (untyped int constant 140737488355327) overflows int

go版本1.20
windows10
sonic版本最新的1.8.1

**Comment by liuq19** [comment]
are your windows is 32-bit

**Comment by liuq19** [comment]
dup issue  #405
