### ISSUE TITLE
Can we add an API for modifying JSON tag names of struct fields in Sonic library?

### ISSUE THREAD

**Issue by pokeyaro** [bytedance/sonic#442]
I hope that Sonic library can add an API for modifying the JSON tag names of struct fields.

For example, I would like to modify the JSON tag name of the Name field in the User struct from "json:name" to "json:username". Since the tag information is determined at compile time, reflection mechanism is needed to dynamically modify the tag name.

```go
func SetTag(s string) {
    //omit...
    field.Tag = reflect.StructTag(fmt.Sprintf(`json:"%s"`, s))
}
```

**Comment by liuq19** [comment]
This is a simple requirement that can be achieved using reflection. 

Moreover, this requirement is not necessarily related to JSON.

So it is not recommended to add this interface to the Sonic JSON library.

**Comment by AsterDY** [comment]
depulicated with #440
