### ISSUE TITLE
Function loader meta info invalid

### ISSUE THREAD

**Issue by ii64** [bytedance/sonic#445]
Function info can not start with `nameOff` equals 0. 

https://go.googlesource.com/go/+/go1.20.4/src/runtime/symtab.go#1004

Resulting `(*runtime.Func).Name()` return an empty string for function name.

![image](https://github.com/bytedance/sonic/assets/26342994/81e35a72-8843-4ff3-9d2c-49897dec5065)

**Comment by liuq19** [comment]
Fixed by #446
