### ISSUE TITLE
support parse number with high precision as possible in sonic ast

### ISSUE THREAD

**Issue by liuq19** [bytedance/sonic#448]
Support parse number with  high precision as possible.

For example:
1. If number is negative integer, parse number into int64,
2. If number is positive integer, parse number into uint64,
3. Others, parse number into float64.

Now usenumber only cast number to `json.Number`, it is string type. Also, ast not have UseInt64 API. So we can provide a new API, to do it.

**Comment by chenlinli** [comment]
Will the new API be supported？

**Comment by chenlinli** [comment]
这是来自QQ邮箱的假期自动回复
谢谢，您的邮件我已收到。
