### ISSUE TITLE
In linux aarch64 or M1 mac, UseInt64 don't work

### ISSUE THREAD

**Issue by darkness463** [bytedance/sonic#449]
sonic version: v1.9.1

code: 
```
var m map[string]interface{}
api := sonic.Config{
    UseInt64: true,
}.Froze()
s := "{\"aa\": 11}"
_ = api.Unmarshal([]byte(s), &m)
```

The type is still float64.
<img width="307" alt="Xnip2023-06-09_12-20-32" src="https://github.com/bytedance/sonic/assets/11989727/d824de4e-8aa1-4d69-aa49-90e752939d54">

**Comment by liuq19** [comment]
UseIntt64 only works in amd64. 
Are you using another arch, e.g. arm64 or mac m1.
Because sonic fallbacks to `encoding/json` in not-amd64 arch, and `encoding/json` does not supports UseInt64.
