### ISSUE TITLE
suggest add Valid() API

### ISSUE THREAD

**Issue by baijinping** [bytedance/sonic#462]
I'm not sure whether `sonic.ConfigDefault.Valid` is the most concise way to validate JSON data.
If yes, i suggest add sonic.Valid() API for convenience.

compare with other json lib
```go
import (
	"encoding/json"
	"github.com/bytedance/sonic"
	jsoniter "github.com/json-iterator/go"
)

func main() {
	var jsonData = []byte(`{"code":1}`)

	json.Valid(jsonData)
	jsoniter.Valid(jsonData)
	sonic.ConfigDefault.Valid(jsonData)

	// suggestion: sonic.Valid(jsonData)
}
```

**Comment by liuq19** [comment]
LGTM @AsterDY

**Comment by liuq19** [comment]
> I'm not sure whether `sonic.ConfigDefault.Valid` is the most concise way to validate JSON data. If yes, i suggest add sonic.Valid() API for convenience.
> 
> compare with other json lib
> 
> ```go
> import (
> 	"encoding/json"
> 	"github.com/bytedance/sonic"
> 	jsoniter "github.com/json-iterator/go"
> )
> 
> func main() {
> 	var jsonData = []byte(`{"code":1}`)
> 
> 	json.Valid(jsonData)
> 	jsoniter.Valid(jsonData)
> 	sonic.ConfigDefault.Valid(jsonData)
> 
> 	// suggestion: sonic.Valid(jsonData)
> }
> ```

Thanks, could you try it?

**Comment by baijinping** [comment]
sure, TBR https://github.com/bytedance/sonic/pull/470 @liuq19
