### ISSUE TITLE
Missing function body error

### ISSUE THREAD

**Issue by kcaashish** [bytedance/sonic#485]
Hello!

I am getting this error:
```
# github.com/bytedance/sonic/internal/rt
../../go/pkg/mod/github.com/bytedance/sonic@v1.9.2/internal/rt/gcwb.go:102:6: missing function body
../../go/pkg/mod/github.com/bytedance/sonic@v1.9.2/internal/rt/gcwb.go:104:6: missing function body
../../go/pkg/mod/github.com/bytedance/sonic@v1.9.2/internal/rt/gcwb.go:114:6: missing function body
```

I am trying to run the following command in which I get the error:
```
GOARCH=wasm GOOS=js go build -o ./dist/rule.wasm ./cmd/rule.go
```

Using, `go version go1.20.6 linux/amd64` on Fedora 38.

I don't know what context you would need to figure this out. Please let me know if I need to give you anything else.

**Comment by liuq19** [comment]
sonic does not support `wasm`
