### ISSUE TITLE
fix: When array-type nodes call SortKeys(recurse = true), there will always be error reported.

### ISSUE THREAD

**Issue by Borsalinoo** [bytedance/sonic#502]
<img width="966" alt="截屏2023-08-14 20 13 46" src="https://github.com/bytedance/sonic/assets/124269255/e47c3882-9485-4549-a685-96020f2ec904">
<img width="716" alt="截屏2023-08-14 20 27 02" src="https://github.com/bytedance/sonic/assets/124269255/b949e76d-65bb-4762-b539-9bd772666b8a">
Expect compatibility with array-type node.

**Comment by liuq19** [comment]
`SortKeys` is designed for object nodes
