### ISSUE TITLE
to support decoder for any layout of time string

### ISSUE THREAD

**Issue by hzmsrv** [bytedance/sonic#506]
we can not decode "2024-04-13" to a time Var.
 
```
func TestJosnInt64Value(t *testing.T) {
	type Test1 struct {
		Id   int64
		Name string
		Time string
	}
	type Test2 struct {
		Id   int64
		Name string
		Time time.Time
	}
	coder := new(jsonCodec)
	buf, err := coder.Encode(Test1{Id: 12345, Name: "adc", Time: "2024-04-13"})
	if err != nil {

	}
	var test Test2
	err = coder.Decode(buf, &test)
	if err != nil {
		t.Fatal(err)
	}
}
```

**Comment by liuq19** [comment]
`time.Time` is not a standard unmarshalled type, maybe you can define a `unmarshaler`

example like 
https://stackoverflow.com/questions/25087960/json-unmarshal-time-that-isnt-in-rfc-3339-format

**Comment by hzmsrv** [comment]
thanks! but we need a raw type time struct not a custom struct!

**Comment by liuq19** [comment]
a raw type `time.Time` is not unmarshalled by Golang, as `encoding/json`

**Comment by hzmsrv** [comment]
is there any guy to push a request below to FIX this issue

```
func decodeJsonUnmarshaler(vv interface{}, s string) error {
	if v, ok := vv.(*time.Time); ok {
		str := strings.Trim(string(s), `"`)
		now, _ := dateparse.ParseAny(str)
		*v = *(*time.Time)(&now)
	}
	return nil // vv.(json.Unmarshaler).UnmarshalJSON(rt.Str2Mem(s))
}
```

**Comment by hzmsrv** [comment]
the final codes like below!
https://github.com/hzmsrv/sonic/blob/main/internal/decoder/primitives.go

**Comment by liuq19** [comment]
Thanks~

Maybe it will cause a hardcode in `decoderJsonUnmarshaler `. And we will not support it.

If you need specific time layout,  recommend you define a unmarshaler/marshaler

**Comment by hzmsrv** [comment]
Thanks!  I am using it for importing data from different time layouts! since we don't know which time layout the customer will use! so to define a unmarshaler/marshaler is not a good choice!

**Comment by AsterDY** [comment]
Sonic's implementation is not like `json-iterator`'s which can replace the entire type-specific decoder/encoder. At present , we don't consider supporting it, unless `encoding/json` support it
