### ISSUE TITLE
能否提供EmitDefaults的配置项？

### ISSUE THREAD

**Issue by XiaohuaZhou** [bytedance/sonic#509]
### Discussed in https://github.com/bytedance/sonic/discussions/508

<div type='discussions-op-text'>

<sup>Originally posted by **XiaohuaZhou** August 18, 2023</sup>
现状: 字段为默认值就不会被序列化。
诉求: 提供EmitDefaults的配置项, 默认关闭, 用户可以按需打开。</div>

**Comment by XiaohuaZhou** [comment]
就是识别 json:"field_name,omitempty" 中的 omitempty

**Comment by liuq19** [comment]
这里是说提供配置，按需关闭 `omitempty` 这个tag吗？能否给一个详细的 exmaple 示例

**Comment by XiaohuaZhou** [comment]
是的, 需要提供配置按需关闭 omitempty 这个tag
![image](https://github.com/bytedance/sonic/assets/17635323/534e6503-703b-4a4c-82f1-b074fa416e4c)
![image](https://github.com/bytedance/sonic/assets/17635323/0f66f8c4-f12e-47d2-8362-496f5a429d9c)

**Comment by XiaohuaZhou** [comment]
是的, 需要提供配置按需关闭 omitempty 这个tag

示例:
*********************************************************************************************
假设我们有以下的 Go 结构体定义：
type Person struct {
    Name    string `json:"name"`
    Age     int    `json:"age"`
    Address string `json:"address,omitempty"`
}
现在我们想要将一个 Person 实例转换成 JSON 字符串，并且在 JSON 中包含所有字段，即使它们的值是零值或空值。我们可以使用 json.Marshal 函数，并设置 json 标签中的 omitempty 选项为 false，以便在 JSON 中包含所有字段。此外，我们还需要设置 json 标签中的 omitempty 选项为 false，以便在 JSON 中包含所有字段。
p := Person{Name: "Alice", Age: 30}
data, err := json.Marshal(p)
if err != nil {
    log.Fatal(err)
}
fmt.Println(string(data))
输出结果如下：
{"name":"Alice","age":30,"address":""}
可以看到，即使 Address 字段的值为空字符串，它仍然包含在 JSON 中。这是因为我们设置了 json 标签中的 omitempty 选项为 false，以便在 JSON 中包含所有字段。

**Comment by XiaohuaZhou** [comment]
// EmitDefaults specifies whether to render fields with zero values.
	EmitDefaults bool

**Comment by XiaohuaZhou** [comment]
EmitDefaults  对应 google.golang.org/protobuf/encoding/protojson 的 protojson.MarshalOptions.EmitUnpopulated

	// EmitUnpopulated specifies whether to emit unpopulated fields. It does not
	// emit unpopulated oneof fields or unpopulated extension fields.
	// The JSON value emitted for unpopulated fields are as follows:
	//  ╔═══════╤════════════════════════════╗
	//  ║ JSON  │ Protobuf field             ║
	//  ╠═══════╪════════════════════════════╣
	//  ║ false │ proto3 boolean fields      ║
	//  ║ 0     │ proto3 numeric fields      ║
	//  ║ ""    │ proto3 string/bytes fields ║
	//  ║ null  │ proto2 scalar fields       ║
	//  ║ null  │ message fields             ║
	//  ║ []    │ list fields                ║
	//  ║ {}    │ map fields                 ║
	//  ╚═══════╧════════════════════════════╝
	EmitUnpopulated bool

**Comment by liuq19** [comment]
我们是否需要支持这个 flags cc @AsterDY

**Comment by XiaohuaZhou** [comment]
这个功能我们很需要，迫切期望支持。

**Comment by XiaohuaZhou** [comment]
@liuq19 @AsterDY

**Comment by PureWhiteWu** [comment]
@XiaohuaZhou 直接去掉 json tag 里面的 emitempty 应该就行？

**Comment by XiaohuaZhou** [comment]
@PureWhiteWu json tag不能随便修改呀。如果依赖别人的json tag, 那更改不了了。

**Comment by AsterDY** [comment]
有兴趣提交PR吗？相关逻辑 https://github.com/bytedance/sonic/blob/main/internal/encoder/compiler.go#L725

**Comment by PureWhiteWu** [comment]
@XiaohuaZhou 这个行为既然是 omitempty 主动指定的，那么再提供一个选项来 opt-out 很明显是一个没必要的事情，反而会增大长期维护成本，无论是用户的成本还是 sonic 维护者的成本。
建议你和 json tag 负责人沟通是否可以修改。

**Comment by PureWhiteWu** [comment]
另外，这个设计是非常不 make sense 的，因为所谓的 emit default 其实是默认选项，是通过 omit empty 来 opt-out 这个 default 行为的。
如果我们还需要搞个选项来再去 opt-out 这个 opt-out default 行为的行为，那我们是不是还需要搞个选项来 opt-out 这个 out-out 这个 opt-out default 行为的行为的行为？

**Comment by XiaohuaZhou** [comment]
emit default 这个名字只是举例, 例子可能不太恰当。
sonic现在不支持输出全字段的json序列化结果, 我的核心诉求是提供配置按需关闭 omitempty 这个tag, 从而得到全字段的json序列化结果。 @PureWhiteWu

**Comment by XiaohuaZhou** [comment]
> 有兴趣提交PR吗？相关逻辑 https://github.com/bytedance/sonic/blob/main/internal/encoder/compiler.go#L725

我研究一下

**Comment by Percivalll** [comment]
+1 同求这个功能，相关场景并不少见：
https://github.com/golang/protobuf/blob/master/jsonpb/encode.go#L39
