### ISSUE TITLE
怎么替换gin框架里自带的json

### ISSUE THREAD

**Issue by stevenlicode** [bytedance/sonic#512]

**Comment by GuangmingLuo** [comment]
gin 自 1.9.0 版本开始已经默认使用 sonic

**Comment by haorenfsa** [comment]
@GuangmingLuo Are you sure?  just check the gin's code and seems it still needs a sonic build tag
https://github.com/gin-gonic/gin/blob/v1.9.1/internal/json/sonic.go#L5

**Comment by ppd324** [comment]
看源码是需要编译命令-tags="sonic avx"才能启用sonic吧
