### ISSUE TITLE
构建动态结构体

### ISSUE THREAD

**Issue by Chise1** [bytedance/sonic#513]
请问是否存在结构体解析的中间状态，用于在解析json数据的时候使用。是否可以通过构建解析的中间状态实现动态结构体并通过sonic进行json序列化和反序列化？

**Comment by AsterDY** [comment]
可以在具体描述一下你想实现什么业务场景吗？或者看看 ast.Node 泛型能否满足你的需求？

**Comment by AsterDY** [comment]
从字面意思上看，你也可以使用 reflect.StructOf() 动态构造一个 type ， 然后 new 它的对象来传给sonic。可以参考sonic fuzz 代码https://github.com/bytedance/sonic/blob/main/fuzz/struct_fuzz_test.go#L83

**Comment by Chise1** [comment]
thanks.
