### ISSUE TITLE
Unsupported Go version. Supported versions are: 1.15, 1.16, 1.17, 1.18, 1.19

### ISSUE THREAD

**Issue by jiangbo9510** [bytedance/sonic#514]
sonic version: 1.4.0
go version: 1.20
Use go version in go mod , 1.18

**Comment by GuangmingLuo** [comment]
升级下 sonic 版本：https://github.com/bytedance/sonic/releases

**Comment by jiangbo9510** [comment]
> 升级下 sonic 版本：https://github.com/bytedance/sonic/releases

升级到1.10.0就ok了，为啥？

**Comment by liuq19** [comment]
sonic 需要适配 golang 版本 https://github.com/bytedance/sonic/pull/493
