### ISSUE TITLE
do not support go 1.21.0 ?

### ISSUE THREAD

**Issue by ivanlebron** [bytedance/sonic#517]
env:
macos : arm64 
goversion : 1.21.0

result:
WARNING: sonic only supports Go1.16~1.20 && CPU amd64, but your environment is not suitable

**Comment by ivanlebron** [comment]
sonic : v1.10.0

**Comment by AsterDY** [comment]
support 1.21, not support arm

**Comment by ivanlebron** [comment]
Is there a plan to support arm64?
