### ISSUE TITLE
WARNING: sonic only supports Go1.16~1.20 && CPU amd64, but your environment is not suitable

### ISSUE THREAD

**Issue by 7836246** [bytedance/sonic#518]
![image](https://github.com/bytedance/sonic/assets/65436665/53b718f9-79bb-45a1-b73d-b3a922bd09be)

**Comment by ii64** [comment]
Do you use `ast` module?

**Comment by liuq19** [comment]
This warning is as expected and is used to notify users that a low-performance fallback implementation is being used. Additionally, we are providing native support for the ARM architecture.
