### ISSUE TITLE
should encoder and decoder object be shared or created on demand?

### ISSUE THREAD

**Issue by yangcheng** [bytedance/sonic#534]
It's unclear from documentation what's the best practice to use encoder and decoder.

Should I keep a global encoder ? is the object thread-safe?

Thanks

**Comment by liuq19** [comment]
Encoder or decoder is mostly used for some specific configurations, such as decoder with `UseNumber`, or encoder with `SortKeys`.  And there are no benefits to reusing an encoder or decoder. So recommended not to use a shared encoder or decoder.

**Comment by yangcheng** [comment]
good to know that, I was about to use encoder for streaming io as mentioned in https://github.com/bytedance/sonic#streaming-io , no specific configuration, just http write response. is it recommended to simplely use  `Marshal ` ?

**Comment by liuq19** [comment]
> good to know that, I was about to use encoder for streaming io as mentioned in https://github.com/bytedance/sonic#streaming-io , no specific configuration, just http write response. is it recommended to simplely use `Marshal ` ?

yes, if not in streaming scenes or specific configuration,  just use `Marshal`
