### ISSUE TITLE
Can we add a switch to avoid printing the warning? 

### ISSUE THREAD

**Issue by hwbrzzl** [bytedance/sonic#535]
```
WARNING: sonic onlu supportsGo116~1.20 88 CPU amd64, but your environment is not suitable
```

When a third framework uses Sonic and prints this warning, some users get confused.

**Comment by hwbrzzl** [comment]
Thanks for your reply, my environment is Golang 1.21 and macOS, but users should have different systems and Golang versions, I want to find a way to avoid printing the warning, not only for me. Thanks ~

**Comment by liuq19** [comment]
The warning is expected in the unsupported environments for Sonic, and should not be avoided.

**Comment by hwbrzzl** [comment]
Okay, thanks.
