### ISSUE TITLE
loong64 CPU下编译错误

### ISSUE THREAD

**Issue by zzdboy** [bytedance/sonic#538]
E:\Go\pkg\mod\github.com\bytedance\sonic@v1.10.2\internal\rt\gcwb.go:102:6: missing function body
E:\Go\pkg\mod\github.com\bytedance\sonic@v1.10.2\internal\rt\gcwb.go:104:6: missing function body
E:\Go\pkg\mod\github.com\bytedance\sonic@v1.10.2\internal\rt\gcwb.go:114:6: missing function body

**Comment by felix021** [comment]
Sonic 目前只支持 amd64

**Comment by dapeng17951** [comment]
loong64 CPU下编译错误：
C:\Users\32763\go\pkg\mod\github.com\bytedance\sonic@v1.12.3\internal\rt\fastmem.go:145:6: missing function body
riscv64下编译错误：
C:\Users\32763\go\pkg\mod\github.com\bytedance\sonic@v1.12.3\internal\rt\fastmem.go:145:6: missing function body
