### ISSUE TITLE
panic:concurrent map iteration and map write

### ISSUE THREAD

**Issue by ivanlebron** [bytedance/sonic#541]
2023-10-22 15:35:43--------------------------------
fatal error: concurrent map iteration and map write

goroutine 991 [running]:
github.com/bytedance/sonic/internal/encoder.iteratorNext(0xc003200c18?)
        /go/pkg/mod/github.com/bytedance/sonic@v1.10.2/internal/encoder/mapiter.go:150 +0xae
encode_*sys.Message()
        ?:0 +0x15fc
github.com/bytedance/sonic/internal/encoder.encodeTypedPointer(0xc003200c18, 0x2678de0, 0xc0041ebb48, 0x7fd86b654228?, 0x0)
        /go/pkg/mod/github.com/bytedance/sonic@v1.10.2/internal/encoder/primitives.go:83 +0x1be
github.com/bytedance/sonic/internal/encoder.encodeInto(0xc003200c18, {0x2678de0, 0xc0024ee7e0}, 0xc0001602c0?)
        /go/pkg/mod/github.com/bytedance/sonic@v1.10.2/internal/encoder/encoder.go:225 +0xe5
github.com/bytedance/sonic/internal/encoder.Encode({0x2678de0, 0xc0024ee7e0}, 0x7fd8b294d3c8?)
        /go/pkg/mod/github.com/bytedance/sonic@v1.10.2/internal/encoder/encoder.go:182 +0xcf
github.com/bytedance/sonic.frozenConfig.Marshal(...)
        /go/pkg/mod/github.com/bytedance/sonic@v1.10.2/sonic.go:86
github.com/bytedance/sonic.Marshal(...)
        /go/pkg/mod/github.com/bytedance/sonic@v1.10.2/api.go:153

**Comment by liuq19** [comment]
could you add `-race` in tests? There may be a data-race problem

**Comment by ivanlebron** [comment]
this is an accidental phenomenon that is difficult to reproduce

**Comment by AsterDY** [comment]
`go build -race` can show more detailed trace. In general, it is introduced by user pass map between goroutine and use them concurrently, which has no relation with sonic
