### ISSUE TITLE
使用v1.10.2版本数组越界

### ISSUE THREAD

**Issue by zjtaozjtw** [bytedance/sonic#548]
[main] panic: runtime error: slice bounds out of range [317:305]
[main] 
[main] goroutine 255 [running]:
[main] github.com/bytedance/sonic/ast.(*Node).skipNextPair(0xc000a938f0)
[main] 	/go/pkg/mod/github.com/bytedance/sonic@v1.10.2/ast/parser.go:557 +0x1195
[main] github.com/bytedance/sonic/ast.(*Node).skipKey(0xc000a938f0, {0xc000739c75, 0x5})
[main] 	/go/pkg/mod/github.com/bytedance/sonic@v1.10.2/ast/node.go:1246 +0x314
[main] github.com/bytedance/sonic/ast.(*Node).Get(0xc000a938f0, {0xc000739c75, 0x5})
[main] 	/go/pkg/mod/github.com/bytedance/sonic@v1.10.2/ast/node.go:718 +0x96
[main] git.qingteng.cn/ms/service-outgoing/internal/global.(*FilterMap).IsSink(0xc0009fce00, 0xc000486ea0)
[main] 	/workspace/internal/global/common_msg.go:142 +0x3d2
[main] git.qingteng.cn/ms/service-outgoing/internal/processor/filter.Filter.func1()
[main] 	/workspace/internal/processor/filter/filter.go:18 +0x125
[main] created by git.qingteng.cn/ms/service-outgoing/internal/processor/filter.Filter
[main] 	/workspace/internal/processor/filter/filter.go:15 +0x19e

**Comment by AsterDY** [comment]
please give reproducible codes and data

**Comment by GuangmingLuo** [comment]
close due to no future response
