### ISSUE TITLE
编译包体积大问题

### ISSUE THREAD

**Issue by iaping** [bytedance/sonic#559]
<img width="821" alt="tobig" src="https://github.com/bytedance/sonic/assets/15192203/3419c304-26b0-41b9-a320-45011b4cedce">
<img width="539" alt="tobig2" src="https://github.com/bytedance/sonic/assets/15192203/0db7ac86-ee24-441f-9761-cf70aca18a93">

如果我用了sonic包解析json，编译后体积55M，不使用编译后33M，是哪里需要配置吗

**Comment by AsterDY** [comment]
sonic底层实现很复杂，并且为了在不同的cpu feature（sse/avx/avx2）下自动兜底同时引入了多套c汇编代码。所有这个情况符合预期。个人觉得多出来20M对部署影响不大？

**Comment by iaping** [comment]
明白，20M影响不大，确实了是包影响了编译体积就好，感谢答复！
