### ISSUE TITLE
asm2asm的工具最近有开源计划吗?

### ISSUE THREAD

**Issue by guonaihong** [bytedance/sonic#57]
c语言生成的x86汇编转成go汇编的工具, 有计划开源吗?

**Comment by chenzhuoyu** [comment]
> c语言生成的x86汇编转成go汇编的工具, 有计划开源吗?

在我的个人仓库里：https://github.com/chenzhuoyu/asm2asm

**Comment by guonaihong** [comment]
@chenzhuoyu 优秀, 有相关文档介绍下asm2asm背后的一些思路吗, 两种汇编的差异点也行? 我懂一点linux 汇编, 不是太了解go的汇编
最后确认下sonic的背后思路, 就用c语言写parser, 用循环展开法, 或者调用avx 或者sse指令, 最后用gcc或者llvm生成汇编, 最后用asm2asm转成go的汇编.最后在go里面调用?
