### ISSUE TITLE
WARNING: sonic only supports Go1.16~1.20 && CPU amd64, but your environment is not suitable

### ISSUE THREAD

**Issue by sprappcom** [bytedance/sonic#592]
installed golang 1.22

(mind if i ask why there's a limit to the versions supported? is it because of go assembly code inside?)

golang version 1.22 has speed improvement. so just wondering if the message can go away or something.

sonic is part of my golang main module and not sure which part of the system is using it but it's the only one so far with this message. can this "feature" be fixed in future?

the program is working even with the warning msg generated.

**Comment by anyongjin** [comment]
The maintainer of this repository made it compatible with version 1.22 in the commit 3f15f269ee, but a stable release for version 1.22 has not yet been released. So, if you need version 1.22, you need to run: `go get github.com/bytedance/sonic@3f15f269ee`

**Comment by sprappcom** [comment]
ok thx.
