### ISSUE TITLE
go 1.22.0 build error

### ISSUE THREAD

**Issue by UallenQbit** [bytedance/sonic#595]
go version go1.22.0 windows/amd64

# github.com/bytedance/sonic/loader
C:\Users\Microsoft\go\pkg\mod\github.com\bytedance\sonic@v1.10.2\loader\funcdata.go:37:32: undefined: _func
C:\Users\Microsoft\go\pkg\mod\github.com\bytedance\sonic@v1.10.2\loader\funcdata.go:74:12: undefined: moduledata
C:\Users\Microsoft\go\pkg\mod\github.com\bytedance\sonic@v1.10.2\loader\funcdata.go:77:18: undefined: moduledata
C:\Users\Microsoft\go\pkg\mod\github.com\bytedance\sonic@v1.10.2\loader\funcdata.go:188:28: undefined: compilationUnit
C:\Users\Microsoft\go\pkg\mod\github.com\bytedance\sonic@v1.10.2\loader\stubs.go:26:22: undefined: moduledata
C:\Users\Microsoft\go\pkg\mod\github.com\bytedance\sonic@v1.10.2\loader\stubs.go:30:26: undefined: moduledata
C:\Users\Microsoft\go\pkg\mod\github.com\bytedance\sonic@v1.10.2\loader\stubs.go:38:27: undefined: moduledata
C:\Users\Microsoft\go\pkg\mod\github.com\bytedance\sonic@v1.10.2\loader\wrapper.go:102:10: undefined: Load
C:\Users\Microsoft\go\pkg\mod\github.com\bytedance\sonic@v1.10.2\loader\wrapper.go:177:13: undefined: Load

**Comment by AsterDY** [comment]
update to v1.11
