### ISSUE TITLE
Depress WARNING: sonic only supports Go1.16~1.22 && CPU amd64, but your environment is not suitable on Apple Chip Macs

### ISSUE THREAD

**Issue by gonejack** [bytedance/sonic#598]
Hi, Author.

This warning shows up a lot and kind of tiring, could sonic exclude this WARNING for arm64+darwin enviroment as Apple certainly has not sold any servers built with Apple chips + MacOS yet.

**Comment by AsterDY** [comment]
This warning is used to warn users who may ignore compatibility between different envs. Maybe add a environment to omit it is a applicable option

**Comment by AsterDY** [comment]
LGTM

**Comment by jiabowen-tal** [comment]
+10086
