### ISSUE TITLE
Support golang v1.22

### ISSUE THREAD

**Issue by rts-gordon** [bytedance/sonic#609]
Hi there, 

  My application use golang version: v1.22.1,  sonic version: v1.10.2.

  I upgrade golang to v1.22.1, there are some warnings for Sonic in VSC:
 ` WARNING: sonic only supports Go1.16~1.20 && CPU amd64, but your environment is not suitable`
  
![image](https://github.com/bytedance/sonic/assets/5645296/fbc54626-89b7-4bfc-b740-e122ff551e77)

  Some invalid char in Json parse failed with golang v1.22, but they can be parsed with golang v1.21.
  `invalid character '\\t' in string literal, message: {\"server_id\":\"live11\", \"comment\":\"\ufffd\t\"}`

  Is there a plan for Sonic to support golang v1.22? 
  Thank you.

**Comment by AsterDY** [comment]
See release log first, PLS
