### ISSUE TITLE
frozenconfig.Unmarshal consumes a large amount of memory.

### ISSUE THREAD

**Issue by Lambert-Sea** [bytedance/sonic#612]
![image](https://github.com/bytedance/sonic/assets/131238873/c06b9ff2-10ac-4902-9668-8444173a869b)

As the project runs, Sonic processes an increasing number of conversions between strings and structs. With this, the frozenconfig.Unmarshal method gradually consumes more memory, sometimes suddenly occupying over 80% of the memory. Restarting the service is necessary to release this memory, but the problem reoccurs after a period of time.

What could be the cause of this issue, and how can it be resolved?

**Comment by AsterDY** [comment]
Try `CopyString`. If not work, it must be your logic cause (ex: goroutine leak)

**Comment by Lambert-Sea** [comment]
Thanks for your help.
Could you explain why this will happen? so that I can understand this lib well.

**Comment by Lambert-Sea** [comment]
> Try `CopyString`. If not work, it must be your logic cause (ex: goroutine leak)

Thank for your help.

Could you explain why this will happen? so that I can understand this sonic well.

**Comment by AsterDY** [comment]
https://github.com/bytedance/sonic?tab=readme-ov-file#copy-string  Have you read this ?
