### ISSUE TITLE
go: module github.com/cloudwego/iasm@upgrade found (v0.1.0), but does not contain package github.com/cloudwego/iasm/x86_64

### ISSUE THREAD

**Issue by shiyunjin** [bytedance/sonic#620]
github.com/bytedance/sonic imports
        github.com/bytedance/sonic/ast imports
        github.com/cloudwego/base64x imports
        github.com/bytedance/sonic/loader imports
        github.com/bytedance/sonic/internal/abi imports
        github.com/cloudwego/iasm/x86_64: no required module provides package github.com/cloudwego/iasm/x86_64; to add it:
        go get github.com/cloudwego/iasm/x86_64

**Comment by MScuti** [comment]
same situation

**Comment by MScuti** [comment]
temporarily downgrade to version: v1.11.2  fix this error.  @AsterDY

**Comment by fabszabo** [comment]
The package "iasm" has always failed all it's tests: https://github.com/cloudwego/iasm/issues/1

**Comment by felix021** [comment]
Known issue.

Please refer to https://github.com/cloudwego/kitex/issues/1319 for the solution

**Comment by fabszabo** [comment]
I see no reason or proof why that would work. All the tests in that package (even in version 0.0.9) are failing with this exact issue.

**Comment by felix021** [comment]
Sorry for the inconvenience.

This project is ported from a personal repository and we didn't pay attention to the workflow which is using go1.2 (not supported) and ARM64 (also not supported).

The v0.0.9 is just the same as the original version and v0.1.0 introduced incompatible changes and was wrongly set as the latest release.

We've removed v0.1.0 to avoid further confusion and will fix the workflow soon after.

**Comment by fabszabo** [comment]
I have tested it and it does indeed resolve the issue. Thank you @felix021

**Comment by fabszabo** [comment]
@jurilucci-geoin bytedance 1.11.2 does not have this issue in the first place.

> temporarily downgrade to version: v1.11.2 fix this error.
go get github.com/bytedance/sonic@v1.11.2

**Comment by felix021** [comment]
> Sorry for the inconvenience.
> 
> This project is ported from a personal repository and we didn't pay attention to the workflow which is using go1.2 (not supported) and ARM64 (also not supported).
> 
> The v0.0.9 is just the same as the original version and v0.1.0 introduced incompatible changes and was wrongly set as the latest release.
> 
> We've removed v0.1.0 to avoid further confusion and will fix the workflow soon after.

As is explained before, this issue can be solved by:

```bash
go get github.com/cloudwego/iasm@v0.0.9
```

Refer to https://github.com/cloudwego/kitex/issues/1319 for more details.

**Comment by zenire** [comment]
Also experiencing this issue via gin:
`go: mypkg imports
	github.com/gin-gonic/gin imports
	github.com/gin-gonic/gin/internal/json imports
	github.com/bytedance/sonic imports
	github.com/bytedance/sonic/ast imports
	github.com/cloudwego/base64x imports
	github.com/bytedance/sonic/loader imports
	github.com/bytedance/sonic/internal/abi imports
	github.com/cloudwego/iasm/x86_64: module github.com/cloudwego/iasm@latest found (v0.1.0), but does not contain package github.com/cloudwego/iasm/x86_64`

**Comment by AsterDY** [comment]
TIPS: DON'T ALWAYS update your go mod using **`go get -u`**, this is not a recommended way to maintain your dependencies. Just `go get` to **update the dependency you need update**

**Comment by YangruiEmma** [comment]
> Also experiencing this issue via gin:
> 
> ```
>  go: mypkg imports
> 	github.com/gin-gonic/gin imports
> 	github.com/gin-gonic/gin/internal/json imports
> 	github.com/bytedance/sonic imports
> 	github.com/bytedance/sonic/ast imports
> 	github.com/cloudwego/base64x imports
> 	github.com/bytedance/sonic/loader imports
> 	github.com/bytedance/sonic/internal/abi imports
> 	github.com/cloudwego/iasm/x86_64: module github.com/cloudwego/iasm@latest found (v0.1.0), but does not contain package github.com/cloudwego/iasm/x86_64
> ```

sorry, this issue can be solved by:
```
go get github.com/cloudwego/iasm@v0.0.9
```
later will release new version to resolve this issue

**Comment by keepsmile8** [comment]
go get github.com/cloudwego/iasm@latest

go: github.com/chenzhuoyu/iasm@v0.9.1: reading https://goproxy.io/github.com/chenzhuoyu/iasm/@v/v0.9.1.mod: 404 Not Found
        server response: not found: github.com/chenzhuoyu/iasm@v0.9.1: invalid version: unknown revision v0.9.1

**Comment by GuangmingLuo** [comment]
1. update cloudwego/iasm to v0.2.0
2. update bytedance/sonic to v1.11.4+
@keepsmile8
