### ISSUE TITLE
github.com/bytedance/sonic/loader@v0.1.0: verifying go.mod: checksum mismatch

### ISSUE THREAD

**Issue by yangyile1990** [bytedance/sonic#622]
```
go get github.com/bytedance/sonic/loader@v0.1.0
```
```
go: github.com/cloudwego/base64x@v0.1.3 requires
        github.com/bytedance/sonic/loader@v0.1.0: verifying go.mod: checksum mismatch
        downloaded: h1:ncP89zfokxS5LZrJxl5z0UJcsk4M4yY2JpfqGeCtNLU=
        sum.golang.org: h1:UmRT+IRTGKz/DAkzcEGzyVqQFJ7H9BqwBO3pm9H/+HY=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by yangyile1990** [comment]
use this not use others
```
GOPROXY=https://proxy.golang.org,direct
```

**Comment by AsterDY** [comment]
This is because I push unexpectedly delete the tag and push it again. You can resolve this through two options:
- clean you mod cache `go clean -modcache` and repull all dependency agin
- update to sonic v1.11.6

**Comment by zhuwensi** [comment]
same here.

**Comment by zhuwensi** [comment]
> This is because I push unexpectedly delete the tag and push it again. You can resolve this through two options:
> 
> * clean you mod cache `go clean -modcache` and repull all dependency again
> * update to sonic v1.11.6
>   Sorry for disturbing. We will continue to work on making sonic more reliable and stable
```
go clean -modcache
```
does not help.
And one-api project depends on this module.

**Comment by zhuwensi** [comment]
> This is because I push unexpectedly delete the tag and push it again. You can resolve this through two options:
> 
> * clean you mod cache `go clean -modcache` and repull all dependency again
> * update to sonic v1.11.6
>   Sorry for disturbing. We will continue to work on making sonic more reliable and stable

Hi, with `go clean -modcache`, the error still exists. maybe other reasons?

**Comment by felix021** [comment]
> > This is because I push unexpectedly delete the tag and push it again. You can resolve this through two options:
> > 
> > * clean you mod cache `go clean -modcache` and repull all dependency again
> > * update to sonic v1.11.6
> >   Sorry for disturbing. We will continue to work on making sonic more reliable and stable
> 
> Hi, with `go clean -modcache`, the error still exists. maybe other reasons?

Update to the latest version of sonic should solve this.

**Comment by zhuwensi** [comment]
> ```shell
> go get github.com/bytedance/sonic@latest
> ```

Running `go get github.com/bytedance/sonic@latest`, it shows the same error:
```
go: github.com/cloudwego/base64x@v0.1.3 requires
        github.com/bytedance/sonic/loader@v0.1.0: verifying go.mod: checksum mismatch
        downloaded: h1:ncP89zfokxS5LZrJxl5z0UJcsk4M4yY2JpfqGeCtNLU=
        sum.golang.org: h1:UmRT+IRTGKz/DAkzcEGzyVqQFJ7H9BqwBO3pm9H/+HY=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
```

I think this is because base64x depends on it. (and many other modules depend on sonic/loader@v0.1.0)
```
33 require (
 39     github.com/bytedance/sonic v1.11.6 // indirect
 41     github.com/cloudwego/base64x v0.1.3 // indirect  ======> here throws error.
```

**Comment by AsterDY** [comment]
try go get -u

**Comment by zhuwensi** [comment]
> try go get -u

`go get -u` the same error.

**Comment by AsterDY** [comment]
execute `go clean -modcache` and `rm go.sum` first, then modify sonic's and base64x's (if depends) versions to the latest in "go.mod", finally `go mod tidy`
