### ISSUE TITLE
使用 marshal 方法出现问题 _blankCharsMask overflows int

### ISSUE THREAD

**Issue by jrovis** [bytedance/sonic#628]
Sonic 版本 v1.11.6

使用 sonic.Marshal() 方法时，报错类型溢出，报错信息如下

```bash
# github.com/bytedance/sonic/ast
../go/pkg/mod/github.com/bytedance/sonic@v1.11.6/ast/decode.go:40:25: _blankCharsMask (untyped int constant 4294977024) overflows int
```

**Comment by AsterDY** [comment]
请提供可复习的数据和代码

**Comment by maxid** [comment]
GOOS=linux GOARCH=arm go build -ldflags "-s -w" -o linux_arm32 .
# github.com/bytedance/sonic/ast
vendor/github.com/bytedance/sonic/ast/decode.go:40:25: _blankCharsMask (untyped int constant 4294977024) overflows int
make: *** [build_linux] Error 1

构建 arm32 应用时也出想类似问题

**Comment by AsterDY** [comment]
目前不支持任何32位环境哈，我们后续加个主动提醒
