### ISSUE TITLE
github.com/bytedance/sonic/ast not support ARM32 "_blankCharsMask overflows int"

### ISSUE THREAD

**Issue by maxid** [bytedance/sonic#631]
GOOS=linux GOARCH=arm go build -ldflags "-s -w" -o linux_arm32 .

github.com/bytedance/sonic/ast
vendor/github.com/bytedance/sonic/ast/decode.go:40:25: _blankCharsMask (untyped int constant 4294977024) overflows int
make: *** [build_linux] Error 1

**Comment by AsterDY** [comment]
sorry, sonic cannot suport 32-bit arch at present

**Comment by maxid** [comment]
> sorry, sonic cannot suport 32-bit arch at present

32-bit is usually used extensively in edge computing. It is recommended to support it
