### ISSUE TITLE
如何将Node类型再转换成json string

### ISSUE THREAD

**Issue by baijian** [bytedance/sonic#64]
a := `{"name":"sam","info":{"age":10,"high":"x"}}`
obj, _ = sonic.GetFromString(a)
obj_info := obj.GetByPath("info")
new_high := `"y"`
new_node, _  := sonic.GetFromString(new_high)
obj_info.Set("high",  new_node)

//fmt.Println(obj)

我的使用场景是将json里面的info.high的指改了，然后现在要获取修改后的json格式的字符串，请问要怎么获取?

**Comment by AsterDY** [comment]
ast的序列化能力还没支持，打算过段时间支持上
