### ISSUE TITLE
在启用cgo环境中的情况下，编译出错ast\decode.go:31:29: cannot use 4294977024 (untyped int constant) as int value in constant declaration (overflows)

### ISSUE THREAD

**Issue by YanCastle** [bytedance/sonic#643]
完整错误：
# github.com/bytedance/sonic/ast
C:\Users\Administrator\go\pkg\mod\github.com\bytedance\sonic@v1.11.7\ast\decode.go:31:29: cannot use 4294977024 (untyped int constant) as int value in constant declaration (overflows)

**Comment by YanCastle** [comment]
原因是在32位系统下，_blankCharsMask 所对应的值 4294977024 超出了int类型的范围导致的

**Comment by liuq19** [comment]
这个是已知问题，sonic 目前不支持 32位

**Comment by AsterDY** [comment]
repeated issue #631
