### ISSUE TITLE
Error: relocation target github.com/bytedance/sonic/internal/rt.StartProf not defined

### ISSUE THREAD

**Issue by xhd2015** [bytedance/sonic#648]
Is amd64 the only supported arch?

This issue is raised when trying xgo with sonic, see https://github.com/xhd2015/xgo/issues/194.

Reprodue:
```sh
git clone --depth=1 https://github.com/bytedance/sonic
cd sonic
mkdir -p ./internal/rt_main
cat > ./internal/rt_main/main.go <<'EOF'
package main

import "github.com/bytedance/sonic/internal/rt"

func main() {
	rt.StartProf()
}
EOF

GOARCH=arm64 go build -o /dev/null ./internal/rt_main
```

Error:
```sh
# github.com/bytedance/sonic/internal/ir_main
main.main: relocation target github.com/bytedance/sonic/internal/rt.StartProf not defined
```

_Originally posted by @xhd2015 in https://github.com/xhd2015/xgo/issues/194#issuecomment-2149142800_

**Comment by AsterDY** [comment]
这个是内部函数不暴露给用户，为啥要用。。。

**Comment by AsterDY** [comment]
This is a internal function, why you use it ?!

**Comment by xhd2015** [comment]
I'm curious also, what's this function for?

**Comment by liuq19** [comment]
If as build tag, the `Unmarshal/Decode/...` caller should not touch this function in arm64.  It will call encoding/json now.

**Comment by xhd2015** [comment]
> If as build tag, the `Unmarshal/Decode/...` caller should not touch this function `rt.StartProf()` in arm64. It will call encoding/json now.
> 
> https://github.com/bytedance/sonic/blob/main/decoder/decoder_compat.go#L1

Thanks, will let the user provide more details.
