### ISSUE TITLE
支持对一个json的一个value的search,找出对应的path

### ISSUE THREAD

**Issue by baijian** [bytedance/sonic#65]
使用场景如下:

{
  "name": "test",
  "members": [
    {
       "name": "name1"
       "age": 12,
    },
    {
      "name": "name2",
      "age": 22,
    }
  ],
  "adminMembers" [
   {
       "name": "name3"
       "age": 12,
    },
    {
      "name": "name4",
      "age": 22,
    }
  ],
}
如上的一个json，我用这样的一个json来存储信息，一般情况下我知道path可以找出某个人的age，另外一种场景就是我现在知道一个人的name，想知道他的path，然后也就可以通过path知道这个人的信息以及其他信息了.
请问是否可以支持如上的功能?

**Comment by AsterDY** [comment]
可以先通过已有的迭代器功能来实现
