### ISSUE TITLE
Incompatible with Go 1.23, which doesn't allow //go:linkname to internal symbols, including to runtime package

### ISSUE THREAD

**Issue by stefanb** [bytedance/sonic#660]
While testing Go 1.23 rc1 in 
* https://github.com/Homebrew/homebrew-core/pull/175310
 
there was an error:
````
  # github.com/hdt3213/rdb
  link: github.com/bytedance/sonic/ast: invalid reference to encoding/json.safeSet
````

Go 1.23 no longer allows `//go:linkname * runtime.*` link instructioins, see 
* https://tip.golang.org/doc/go1.23#linker
* https://github.com/golang/go/issues/67401

It is used several times in this module, see:
https://github.com/search?q=repo%3Abytedance%2Fsonic%20linkname&type=code

**Comment by xin-hao-awx** [comment]
got the same issue from `cloudwego/hertz`.

**Comment by AsterDY** [comment]
We are handling this. Please wait for a while

**Comment by stefanb** [comment]
Thanks, i see you have already 
* https://github.com/bytedance/sonic/issues/637
