### ISSUE TITLE
[Bug] after install sonic on go1.23,get error .# github.com/bytedance/sonic/internal/rt missing function body

### ISSUE THREAD

**Issue by lhalcyon** [bytedance/sonic#689]
```
# github.com/bytedance/sonic/internal/rt
C:\Users\Administrator\go\pkg\mod\github.com\bytedance\sonic@v1.12.1\internal\rt\fastmem.go:145:6: missing function body
# github.com/bytedance/sonic/decoder
C:\Users\Administrator\go\pkg\mod\github.com\bytedance\sonic@v1.12.1\decoder\decoder_compat.go:95:33: types.SPACE_MASK (untyped int constant 4294977024) overflows int
```
I tried clean rebuild , did not solve it . anyone solve it ?

**Comment by liuq19** [comment]
could you provide `go env`

**Comment by lhalcyon** [comment]
> Referen

set GO111MODULE=
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=D:\Go\pkg\tool\windows_386
set GOVCS=
set GOVERSION=go1.23.0
set GODEBUG=
set GOTELEMETRY=local
set GOTELEMETRYDIR=C:\Users\Administrator\AppData\Roaming\go\telemetry
set GCCGO=gccgo
set GO386=sse2
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\Administrator\AppData\Local\Temp\go-build592717738=/tmp/go-build -gno-record-gcc-switches

**Comment by liuq19** [comment]
sonic now not support windows or 32-bits

**Comment by lhalcyon** [comment]
Thank u for reply. I see , I 'll reinstall and try .
