### ISSUE TITLE
There is an panic at github.com/bytedance/sonic/internal/decoder/errors.(*MismatchTypeError).Error

### ISSUE THREAD

**Issue by yuanjize** [bytedance/sonic#692]
There is an nil pointer panic in my prod env.

`runtime error: invalid memory address or nil pointer dereference
`
```
github.com/bytedance/sonic/internal/decoder/errors.(*MismatchTypeError).Error(0x2ff8980?)
	:1 +0x25
```
The code just like:

```
var sonicConfig = sonic.Config{
	EscapeHTML: true,
}.Froze()

err:=sonicConfig.Unmarshal(data, v)
if err!=nil{
  print(err.Error())
}
```
It panic when i call `err.Error()`

**Comment by liuq19** [comment]
Thanks, could you provide minimal reproducible codes, we will investigate it

**Comment by yuanjize** [comment]
Hi @liuq19, I find you have push an fix commit. But it only for main branch. Can we use main branch in our prod environment? It is safe?

**Comment by liuq19** [comment]
we will publish the version later

**Comment by yuanjize** [comment]
@liuq19 Thank you very much

**Comment by liuq19** [comment]
pls update into v1.12.2
