### ISSUE TITLE
link: github.com/bytedance/sonic/ast: invalid reference to encoding/json.safeSet (Go 1.23.0/macOS 12.6)

### ISSUE THREAD

**Issue by Alvazz** [bytedance/sonic#697]
follow this https://www.cloudwego.io/docs/hertz/getting-started/ step. get this error.

link: github.com/bytedance/sonic/ast: invalid reference to encoding/json.safeSet

**Comment by liuq19** [comment]
update sonic to the latest version

**Comment by robberphex** [comment]
fixed at https://github.com/bytedance/sonic/commit/121df0ab8e71d27b4da35d6d94aca5a123351ce1
