### ISSUE TITLE
Compilation error on armv7: missing function body in fastmem.go:145

### ISSUE THREAD

**Issue by axliupore** [bytedance/sonic#699]
# Description
I encountered a compilation error when using the `github.com/bytedance/sonic` package on an armv7 architecture.The error message is:
- 38.96 # github.com/bytedance/sonic/internal/rt
- 38.96 /go/pkg/mod/github.com/bytedance/sonic@v1.12.1/internal/rt/fastmem.go:145:6: missing function body
This error occurs when trying to compile my Go application, which depends on the `github.com/bytedance/sonic` package. The same code compiles successfully on amd64 and arm64 architectures, but fails on armv7
<img width="1064" alt="image" src="https://github.com/user-attachments/assets/afae2f2e-4818-4e11-b8fb-5b24da5f83f9">

**Comment by liuq19** [comment]
sonic does not  support 32-bit architecture, we will fixed it to make it fallback into `encoding/json`

**Comment by axliupore** [comment]
> sonic does not support 32-bit architecture

Thanks for your reply
