### ISSUE TITLE
太多内存占用

### ISSUE THREAD

**Issue by Nyx2022** [bytedance/sonic#702]
![image](https://github.com/user-attachments/assets/9d0f004d-fdae-41ed-b0a5-da86f424d3e5)

我做的一个2分钟的火焰兔，可以看到， 我使用的是sonic的sonic.ConfigFastest.NewEncoder和 sync.pool的方式，但是内存占用还是这么高，建议优化一下。我使用的是sonic1.12.3版本+golang 1.23.2

**Comment by AsterDY** [comment]
![image](https://github.com/user-attachments/assets/4738217c-9a0f-4e92-a598-422619ee925e)
你这个是json.Marshaler里面自己调用的std，和sonic没关系。。
