### ISSUE TITLE
 有方法让sonic.ConfigFastest.NewEncoder强制接管marshal方法吗

### ISSUE THREAD

**Issue by Nyx2022** [bytedance/sonic#705]
接 https://github.com/bytedance/sonic/issues/702 ，关的太快了，
确实可以看到cmap这个库自己实现了marshaljson这个方法，然后使用了goalng自带的json库，dao'z导致使用sonic变成了寂寞。所以我想问，sonic有办法忽略函数的marshaljson函数吗

**Comment by AsterDY** [comment]
没有。自己写个util库wrap一下。做好业务代码统一约束才是最佳实践

**Comment by xiusin** [comment]
> 但是很多第三方库使用的是golang自带的json库啊，我怎么约束

更快的方法是把/dir/go/src里的代码删了换成这个 😂

**Comment by nicoxb** [comment]
在go.mod中使用replace encoding/json => github.com/bytedance/sonic v1.xx.xx
