### ISSUE TITLE
Is there a plan to expose the internal decoder for buffer use case?

### ISSUE THREAD

**Issue by spacewander** [bytedance/sonic#711]
In the current implementation, each Unmarshal will create a new decoder:
https://github.com/bytedance/sonic/blob/4a3e8af9a9385825edb6c2cee735176995442c8a/sonic.go#L113-L124

There is already a Reset method in the underlying decoder, however, only the streaming decoder can call it:
https://github.com/bytedance/sonic/blob/4a3e8af9a9385825edb6c2cee735176995442c8a/internal/decoder/api/stream.go#L90

In our scene, we process fixed JSON string and want to cache the decoder instead of creating a new one each call. Wrapping the fixed JSON strings as an io stream is unavailable so we can't use StreamDecoder.

It would be helpful to provide a way to expose the internal decoder, for example, under the name "BufferDecoder" and so on. We would like to contribute if this is acceptable.

**Comment by AsterDY** [comment]
I didn't get it. Decoder only holds the string you pass, there is no buffer..

**Comment by spacewander** [comment]
What I mean by using "buffer" is to refer to a new kind of Decoder that is different from the current exposed Decoder.

In the current implementation, the `NewDecoder` always returns a `StreamDecoder`:
https://github.com/bytedance/sonic/blob/e2ff8ac5e787050108f6ac68944d0e6fb1ae3553/sonic.go#L139-L143

The StreamDecoder accepts an IO stream, and decodes data from it.

Meanwhile, there could be a `BufferDecoder`, which accepts a JSON string and uses `Reset` to clear the state when it wants to decode another JSON string.

**Comment by AsterDY** [comment]
Why not directly use sonic/decoder/NewDecoder()? It can do everythin including set options

**Comment by spacewander** [comment]
Thanks! That's what I need.
