### ISSUE TITLE
建议添加字段初始化函数接口

### ISSUE THREAD

**Issue by Nyx2022** [bytedance/sonic#714]
我在一个复杂的struct中，如果使用了除golang自带类型之外，就会没办法提前初始化变量，而sonic又会自动去反射调用对应库的marshaljson和unmarshaljson，这个时候就会出错（因为不是每一个第三方库都只需要实例化结构体就行，里面会有很多不暴露的属性需要初始化），所以建议添加一个接口或函数，比如withInitFuncs，由用户传递一个sonic在反序列化过程中发现字段为nil的时候，先调用初始化函数，再调用unmarshaljson函数。谢谢

**Comment by AsterDY** [comment]
obj不是你传给sonic的么？为啥不能在调用unmarshal之前先设置好没理解
