### ISSUE TITLE
go 1.17 support

### ISSUE THREAD

**Issue by yuzhichang** [bytedance/sonic#75]
`internal/loader/funcdata_invalid.go:23:11: panic("Unsupported Go version. Supported versions are: 1.15, 1.16")`

**Comment by chenzhuoyu** [comment]
There are a lot of work to do, since Go 1.17 introduces the Register ABI, which might break a lot of things. We are investigating on this.

**Comment by ericuni** [comment]
any progress?

**Comment by chenzhuoyu** [comment]
@ericuni Still working in progress. There is a branch `feat/go117`, all the Go 1.17 related works are done in this branch.

**Comment by geraldstanje** [comment]
can you also make a comparison with fastjson library https://github.com/valyala/fastjson?

**Comment by chenzhuoyu** [comment]
@yuzhichang Go 1.17 support was merged.

**Comment by chenzhuoyu** [comment]
> can you also make a comparison with fastjson library https://github.com/valyala/fastjson?

Pull requests are welcomed ;)

**Comment by harshavardhana** [comment]
@chenzhuoyu can you please add a new tag v1.0.0-rc.3? for us `go.mod` users?
